module.exports =  {
  "e_103015": "Your leverage is not synchronized with frontend setting. Please adjust and try again",
  "e_103016": "Order amount exceeds the limit of {max amount}.",
  "e_103017": "Order amount is less than minimum amount of {min amount}.",
  "e_103022": "TP price must be greater than order price. / SL price must be less than order price",
  "e_103021": "TP price must be greater than latest price. / SL price must be less than latest price",
  "e_undefined": "TP price must be less than order price. SL price must be greater than order price.",
  "e_103005": "Lack of balance.",
  "e_103018": "Your account is not bound by a specific contract.",
  "e_103019": "Order submission time exceeds the system's maximum limit.",
  "e_103020": "Order cancelation time exceeds the system's maximum limit.",
  "e_107004": "This symbol is offline.",
  "e_107005": "This symbol trading has been paused.",
  "e_107006": "Order will trigger position liquidation. Please try again.",
  "e_107007": "Open and close positions simultaneously is not allowed.",
  "e_107008": "Your position is already closed.",
  "e_107009": "Your position is in liquidation delegation.",
  "e_107010": "Your position volume is not enough.",
  "e_107011": "Your position does not exist.",
  "e_107014": "Substract margin will trigger position liquidation warning.",
  "e_107015": "Position margin can't be less than base limit with adjusting leverage.",
  "e_107016": "Your asset is in liquidation delegation.",
  "e_107017": "Your available balance is not enough.",
  "e_107018": "The number of your plan orders exceeds the system's maximum limit.",
  "e_107019": "The order's leverage exceeds the system's upper limit.",
  "e_107020": "The order's leverage is below the system's lower limit.",
  "e_107021": "The deviation between the trigger price of the plan order and the current price is too large.",
  "e_107022": "The plan order's life cycle exceeds the system's upper limit.",
  "e_107023": "The plan order's life cycle is below the system's lower limit.",
  "e_107024": "This symbol is not found!",
  "e_107025": "The activation price must be lower than the latest price for buy order.",
  "e_107026": "The activation price must be higher than the latest price for sell order.",
  "e_107027": "Leverage reduction is not supported with open positions in isolated margin mode.",
  "e_107028": "Order has been filled or canceled.",
  "e_111000": "Master's copy order can only be closed at market price!",
  "e_111001": "Only users with copy account assets less than 100 USDT can be removed.",
  "e_111002": "You currently have a copy position and cannot remove this user. Please close the position and try again.",
  "e_111003": "You cannot copy others because you are a master trader.",
  "e_111004": "Failed to copy due to the number of followers of the master exceeding the upper limit.",
  "e_111005": "You are unable to apply now as you are currently in a blocked period.",
  "e_111006": "You currently have copied other masters and cannot apply to be a master.",
  "e_111007": "Copy order does not support this function.",
  "e_111008": "You currently have a position in this pair, and the trading pair cannot be canceled temporarily. Please close the position and try again.",
  "e_111009": "Sorry! This Master only allows his invitees to copy him.",
  "e_111010": "Copy Trading is under maintenance.",
  "e_900000": "Request success.",
  "e_900001": "Invalid request.",
  "e_900002": "Not logged in or login authentication failed.",
  "e_900003": "Illegal access is forbidden.",
  "e_900004": "No access permission.",
  "e_900005": "Server error.",
  "e_900006": "No results found.",
  "e_900007": "The request parameter is illegal.",
  "e_900008": "Close order failed due to no position or invalid position status.",
  "e_900009": "Illegal request.",
  "e_900010": "System error.",
  "e_900011": "Access too often.",
  "e_900012": "System time invalid.",
  "e_900014": "The number of exports exceeds the system's maximum limit.",
  "e_103029": "Preset TP price must be less than latest price. Preset SL price must be greater than latest price.",
  "e_103028": "Preset TP price must be less than order price. Preset SL price must be greater than order price.",
  "e_103027": "TP price must be greater than order price. SL price must be less than order price.",
  "e_103026": "TP price must be less than order price. SL price must be greater than order price.",
  "e_103006": "Order Invalid.",
  "e_103013": "The maximum leverage for pure trading bonus users to open a position is {leverage}.",
  "e_103011": "The account with bonus cannot be opened for both long and short positions.",
  "e_103007": "Order is finished, it can't be revised.",
  "e_103010": "Order type is conflict with current position or order type.",
  "e_103012": "The pure bonus account cannot be opened for both long and short positions.",
  "e_103014": "You have pending orders in cross margin mode. Please cancel them before adjusting your leverage."
}