module.exports =  {
  "e_0": "Success",
  "e_10": "no repeatable request(usercenter)",
  "e_12307": "Please enable at least two security verifications.",
  "e_1706": "Invalid username",
  "e_1704": "Login passwords are the same",
  "e_1702": "Wrong original login password",
  "e_3504": "scyToken error",
  "e_3503": "mfaToken error",
  "e_3501": "gwToken error",
  "e_1112": "Account already registered",
  "e_1108": "Wrong invitation code",
  "e_1106": "Invalid email address",
  "e_1103": "Invalid phone number",
  "e_1006": "Account is disabled, please contact the main account",
  "e_1008": "User not exists",
  "e_1009": "The financial account is not allowed to log in to the web/app station.",
  "e_1010": "Your phone already bound",
  "e_1011": "This Phone already bound",
  "e_1012": "Your phone not bound",
  "e_1015": "Your mail not bound",
  "e_1016": "Google authenticator not bound",
  "e_1018": "Google authenticator reload",
  "e_1013": "Your mail already bound",
  "e_1014": "This Mail already bound",
  "e_1017": "Google authenticator already bound",
  "e_1023": "Not support account",
  "e_1029": "user has invited people",
  "e_1030": "Not support invite no",
  "e_1031": "invite code does exist",
  "e_1033": "invite code size limit exceed",
  "e_1005": "Account is frozen due to security policies. Please contact customer service.",
  "e_1002": "Invalid username or password, you have %d chances to retry",
  "e_1070": "client id not found",
  "e_3008": "The account is abnormal, please try again later",
  "e_1091": "The main account is unavailable.",
  "e_3004": "Account is frozen due to security policies, please try again after %d hours",
  "e_3003": "Account is frozen due to security policies, please try again after %d hours",
  "e_3002": "Account is frozen due to security policies, please try again after %d hours",
  "e_3001": "Account is frozen due to security policies, please try again after %d hours",
  "e_1092": "Institutional KYC verification not passed.",
  "e_1093": "Sub-account creation limit reached.",
  "e_1094": "Your account has been cancelled",
  "e_1095": "Your account type does not support cancel",
  "e_1101": "Copy string literal text to the clipboard",
  "e_1500": "Header X-BM-CLIENT invalid",
  "e_1501": "Header X-BM-MERCHANT-CLIENT-ID is empty",
  "e_1502": "Header X-BM-MERCHANT-SIGN is empty",
  "e_1503": "Header X-BM-MERCHANT-TIMESTAMP is empty",
  "e_1505": "authorize code invalid",
  "e_1506": "You have submitted too many times, please try again tomorrow",
  "e_2410": "kyc information does not exist",
  "e_1721": "underage",
  "e_1725": "invalid kyc status",
  "e_1726": "Not you sub account",
  "e_1727": "Sub account not allow login app",
  "e_1728": "No permission, please contact our administrator",
  "e_1732": "Invalid Information",
  "e_1733": "Invalid Country/Region",
  "e_1734": "Invalid Birthday",
  "e_1736": "Sorry, only letters(a-z), numbers(0-9), and periods(.), character(! # $ % * / ? ^ + - ` { | } ~ _) are allowed.",
  "e_1737": "Sorry, the character needs to be less than 32 characters.",
  "e_1738": "Sorry, please enter your valid email.",
  "e_1739": "You Haven't Certified Institutional KYC",
  "e_1740": "Your Application Is Pending Or Approved",
  "e_1741": "Your Apply Is Auditing Or Passed",
  "e_1742": "Your Apply Save Error",
  "e_1743": "Invite Relation Error",
  "e_1744": "Cashback Is Greater Than Agent Rebate",
  "e_1745": "Primary certification is required",
  "e_1750": "kyc level does not meet",
  "e_1751": "please check your name",
  "e_1752": "Please check your name (English)",
  "e_1753": "Submission is not supported in authentication.",
  "e_1754": "Special users cannot submit authentication.",
  "e_1755": "Internal users cannot apply for institutional certification.",
  "e_1756": "Sub account denied",
  "e_1757": "BitMart service is not available for the selected area.",
  "e_1758": "The BitMart.HK account and BitMart account are not interchangeable.",
  "e_1759": "Agent already exist",
  "e_1760": "System is abnormal, please try it later",
  "e_1763": "IP is not in the whitelist.",
  "e_1764": "Not mm-bot is forbidden to log in",
  "e_46": "Account not found",
  "e_40": "Request expired",
  "e_36": "Forbidden",
  "e_34": "Has been sent verification code",
  "e_31": "token expired",
  "e_30": "Visit too often, please try again later",
  "e_23": "login code expired",
  "e_18": "Wrong login password，you have %d chances to retry",
  "e_14": "Invalid email verification code，you have %d chances to retry",
  "e_13": "Invalid SMS verification code, you have %d chances to retry",
  "e_12": "Invalid Google verification code，you have %d chances to retry",
  "e_10": "Critical business exception",
  "e_9": "Wrong email verification code",
  "e_8": "Wrong SMS verification code",
  "e_7": "Wrong captcha",
  "e_6": "User not login",
  "e_5": "Service Error",
  "e_4": "Network error",
  "e_3": "Param Error",
  "e_2": "Database Error",
  "e_1": "Failure",
  "e_44004": "DB_ERROR",
  "e_42000": "SYSTEM_ERROR",
  "e_42001": "REQUEST_TOO_FREQUENTLY",
  "e_42003": "USER_NOT_LOGIN",
  "e_42002": "PARAM_NOT_EMPTY",
  "e_42005": "UN_KNOW_DESCRIPTION",
  "e_42006": "LOCALE_CONFIG_NOT_EXIST",
  "e_42007": "UP_LOCALE_NOT_SUPPORT_UPDATE_NAME",
  "e_103015": "Your leverage is not synchronized with frontend setting. Please adjust and try again",
  "e_103016": "Order amount exceeds the limit of {max amount}.",
  "e_103017": "Order amount is less than minimum amount of {min amount}.",
  "e_103022": "TP price must be greater than order price. / SL price must be less than order price",
  "e_103021": "TP price must be greater than latest price. / SL price must be less than latest price",
  "e_undefined": "TP price must be less than order price. SL price must be greater than order price.",
  "e_103005": "Lack of balance.",
  "e_103018": "Your account is not bound by a specific contract.",
  "e_103019": "Order submission time exceeds the system's maximum limit.",
  "e_103020": "Order cancelation time exceeds the system's maximum limit.",
  "e_107004": "This symbol is offline.",
  "e_107005": "This symbol trading has been paused.",
  "e_107006": "Order will trigger position liquidation. Please try again.",
  "e_107007": "Open and close positions simultaneously is not allowed.",
  "e_107008": "Your position is already closed.",
  "e_107009": "Your position is in liquidation delegation.",
  "e_107010": "Your position volume is not enough.",
  "e_107011": "Your position does not exist.",
  "e_107014": "Substract margin will trigger position liquidation warning.",
  "e_107015": "Position margin can't be less than base limit with adjusting leverage.",
  "e_107016": "Your asset is in liquidation delegation.",
  "e_107017": "Your available balance is not enough.",
  "e_107018": "The number of your plan orders exceeds the system's maximum limit.",
  "e_107019": "The order's leverage exceeds the system's upper limit.",
  "e_107020": "The order's leverage is below the system's lower limit.",
  "e_107021": "The deviation between the trigger price of the plan order and the current price is too large.",
  "e_107022": "The plan order's life cycle exceeds the system's upper limit.",
  "e_107023": "The plan order's life cycle is below the system's lower limit.",
  "e_107024": "This symbol is not found!",
  "e_107025": "The activation price must be lower than the latest price for buy order.",
  "e_107026": "The activation price must be higher than the latest price for sell order.",
  "e_107027": "Leverage reduction is not supported with open positions in isolated margin mode.",
  "e_107028": "Order has been filled or canceled.",
  "e_111000": "Master's copy order can only be closed at market price!",
  "e_111001": "Only users with copy account assets less than 100 USDT can be removed.",
  "e_111002": "You currently have a copy position and cannot remove this user. Please close the position and try again.",
  "e_111003": "You cannot copy others because you are a master trader.",
  "e_111004": "Failed to copy due to the number of followers of the master exceeding the upper limit.",
  "e_111005": "You are unable to apply now as you are currently in a blocked period.",
  "e_111006": "You currently have copied other masters and cannot apply to be a master.",
  "e_111007": "Copy order does not support this function.",
  "e_111008": "You currently have a position in this pair, and the trading pair cannot be canceled temporarily. Please close the position and try again.",
  "e_111009": "Sorry! This Master only allows his invitees to copy him.",
  "e_111010": "Copy Trading is under maintenance.",
  "e_900000": "Request success.",
  "e_900001": "Invalid request.",
  "e_900002": "Not logged in or login authentication failed.",
  "e_900003": "Illegal access is forbidden.",
  "e_900004": "No access permission.",
  "e_900005": "Server error.",
  "e_900006": "No results found.",
  "e_900007": "The request parameter is illegal.",
  "e_900008": "Close order failed due to no position or invalid position status.",
  "e_900009": "Illegal request.",
  "e_900010": "System error.",
  "e_900011": "Access too often.",
  "e_900012": "System time invalid.",
  "e_900014": "The number of exports exceeds the system's maximum limit.",
  "e_103029": "Preset TP price must be less than latest price. Preset SL price must be greater than latest price.",
  "e_103028": "Preset TP price must be less than order price. Preset SL price must be greater than order price.",
  "e_103027": "TP price must be greater than order price. SL price must be less than order price.",
  "e_103026": "TP price must be less than order price. SL price must be greater than order price.",
  "e_103006": "Order Invalid.",
  "e_103013": "The maximum leverage for pure trading bonus users to open a position is {leverage}.",
  "e_103011": "The account with bonus cannot be opened for both long and short positions.",
  "e_103007": "Order is finished, it can't be revised.",
  "e_103010": "Order type is conflict with current position or order type.",
  "e_103012": "The pure bonus account cannot be opened for both long and short positions.",
  "e_103014": "You have pending orders in cross margin mode. Please cancel them before adjusting your leverage."
}