export const error_code = {
    '0': 'Successful',
    '1': 'Operation is too Frequent. Please try again later',
    '2': 'Operation is too Frequent. Please try again later',
    '3': 'The requested parameter is invalid. Please try again later',
    '4': 'The server is busy now. Please try again later',
    '5': 'System is abnormal, pls try it later',
    '6': 'Please login first',
    '7': "Captcha validation doesn't match. Please try again",
    '8': "SMS verification code doesn't match. Please try again",
    '9': "Email verification code doesn't match. Please try again",
    '12': "Google Authenticator code doesn't match. You have {0} chance(s) to try",
    '13': "Sms verification code doesn't match. You have {0} chance(s) to try",
    '14': "Email verification code doesn't match. You have {0} chance(s) to try",
    '18': 'Invalid username or password. You have {0} chance(s) to try',
    '19': "Username doesn't exist. Please try again",
    '20': 'The password is incorrect. Please re-enter your password',
    '21': 'Please set your withdrawal password first',
    '22': "Withdrawal password doesn't match. You have {0} chance(s) to try",
    '30': 'Operation is too Frequent. Please try again later',
    '31': 'The verification code has expired, please resend',
    '32': 'The server is busy now. Please try again later',
    '33': 'The server is busy now. Please try again later',
    '34': 'The server is busy now. Please try again later',
    '35': 'Service is unavailable now',
    '36': 'The server is busy now. Please try again later',
    '38': 'Please select the withdrawal address',
    '40': 'Please set your system time to correct time.',
    '41': 'The server is busy now. Please try again later',
    '42': 'The server is busy now. Please try again later',
    '43': 'The server is busy now. Please try again later',
    '44': 'The server is busy now. Please try again later',
    '45': 'The server is busy now. Please try again later',
    '175': 'User Has Certified Institutional KYC',
    '403': 'Please try again later or contact customer service',
    '429': ' Please try again later',
    '500': 'The server is busy now. Please try again later',
    '1000': "Username doesn't exist. Please try again",
    '1001': "Username and password don't match. Please try again",
    '1002': "Username and password don't match. You still have {0} chance(s) to try",
    '1003': "Username doesn't exist. Please try again",
    '1004': 'The server is busy now. Please try again later[1004]',
    '1005': 'Your account may be at risk. Please contact our BitMart customer service',
    '1010': 'This phone number already exists.',
    '1011': 'This phone number already exists.',
    '1012': 'This phone unbound.',
    '1013': 'This email already exists.',
    '1014': 'This email already exists.',
    '1015': 'This email unbound.',
    '1016': 'This Google Authenticator unbound.',
    '1017': 'Google Authenticatoris bound.',
    '1018': 'Please reload the Google Authenticator.',
    '1020': 'You cannot add duplicate memos',
    '1021': 'The whitelist IP set has exceeded the maximum limit',
    '1022': 'Exceeding the maximum creation limit of the API',
    '1029': 'This account has been risk controlled',
    '1030': 'The format of the referral code is incorrect (it can only contain 6-13 letters and numbers, no special characters).',
    '1031': 'The referral code is already occupied.',
    '1032': 'Rebate ratio setting does not exceed the limit.',
    '1033': 'Referral code has exceeded the limit.',
    '1070': 'User id not found',
    '1091': 'Main account is not available',
    '1092': 'Lack of institutional KYC verification',
    '1093': 'Maximum number of sub-accounts',
    '1100': 'The server is busy now. Please try again later',
    '1101': 'Passwords must have at least 8 characters and contain at least two of the following: uppercase letters, lowercase letters, numbers, and symbols.',
    '1102': 'This account has been registered. Please enter another one',
    '1103': 'Please enter a vaild phone number',
    '1105': 'This email address already exists. Please enter a new one',
    '1106': 'Please enter a vaild email address',
    '1108': 'Please enter a vaild invitation code',
    '1109': 'This invitation code has already existed',
    '1110': 'This phone number is already bound to another account',
    '1111': 'This email is already bound to another account',
    '1112': 'This account has been registered. Please enter another one',
    '1203': 'Please enter a vaild phone number',
    '1204': 'Please enter a vaild phone number',
    '1205': 'Please enter a vaild phone number',
    '1206': "This phone number has been bound to another account and can't be used for registration",
    '1207': 'Please bind your account with phone number first',
    '1304': 'Please enter an email address',
    '1305': 'Please enter a vaild email address',
    '1306': 'This email address has been bound to another account',
    '1401': 'Please enable your 2FA via Google Authenticator',
    '1500': 'Please enter a vaild phone number',
    '1501': 'Your account has already been bound your phone number',
    '1502': 'Please bind your account to your phone number first',
    '1505': "SMS verification code doesn't match. Please try again",
    '1507': 'This phone number has been bound to another account',
    '1550': 'Please enter a vaild email address',
    '1551': 'Email has been bound',
    '1552': "Email hasn't been bound",
    '1555': "Email verification code doesn't match. Please try again",
    '1557': 'This email address has been bound to another account',
    '1600': 'Please enter a valid ID number',
    '1601': 'Please enter a valid ID number',
    '1602': 'Please enter a valid ID number',
    '1603': 'Please enter a valid name',
    '1604': 'This ID number has been used on another account',
    '1606': 'Please enter a valid name',
    '1700': 'Two passwords are inconsistent',
    '1701': 'Please enable 2FA via your phone number, email or Google Authenticator',
    '1702': "Login password doesn't match",
    '1703': "Withdrawal password doesn't match",
    '1704': "Your new password can't be the same with your old one",
    '1705': "Your new password can't be the same with your old one",
    '1706': "The username doesn't exist",
    '1721': 'Age must be greater than 18.',
    '1722': 'Age must be less than 75.',
    '1731': 'User Has Certified Personal KYC',
    '1732': 'Invalid Information',
    '1733': 'Invalid Country/Region',
    '1734': 'Invalid Birthday',
    '1739': "You Haven't Certified Institutional KYC",
    '1740': 'Your Application Is Pending Or Approved',
    '1751': 'Please check your name',
    '1752': 'Please check your name（English）',
    '1753': 'Submission is not supported in authentication.',
    '1754': 'Special users cannot submit authentication.',
    '1755': 'Internal users cannot apply for institutional certification.',
    '1800': "This coin can't be traded now",
    '1802': 'Amount must be greater than {0} {1}',
    '1803': 'Maximum exchanging amount {0}',
    '1804': 'Minimum limit order price {0}',
    '1805': 'Minimum limit order total {0}',
    '1806': "Limit order price can't be higher than limit up price {0}",
    '1807': "Limit order price can't be lower than limit down price {0}",
    '1808': 'Total must be greater than {0} {1}',
    '1809': 'Amount must be greater than {0}',
    '1810': 'The trading is closed now',
    '1811': '{0} balance is insufficient',
    '1812': 'You can sell at most {0}',
    '1815': "Everyday's maximum effective limit order times {0}",
    '1816': 'This coin can not be traded',
    '1817': "Sorry, your account doesn't have the operating authorization",
    '1818': 'Maximum limit order price {0}',
    '1819': 'Your order amount exceeds the maximum purchase amount',
    '1820': 'Order prohibited',
    '1823': 'The buy order price cannot be higher than the open price',
    '1824': 'The sell order price cannot be lower than the open price',
    '1900': 'No coin matches',
    '1901': 'Restricted legal currency',
    '1902': 'This coin has no competition',
    '2000': 'No record',
    '2101': 'Please enable 2FA via your phone number, email, or Google Authenticator',
    '2102': 'Your daily available withdrawal times: {0}',
    '2103': 'Minimum withdrawal amount: {0}',
    '2104': 'Maximum withdrawal amount: {0}',
    '2105': 'Insufficient balance',
    '2106': "Users can't exchange with each other within BitMart",
    '2107': 'You have exceeded the daily withdrawal limit. For your safety, please wait 24 hours and try again',
    '2108': 'For safety concerns, please complete the identity Verification Process first',
    '2124': 'No corresponding address was found.',
    '2150': 'Your account does not support Convert',
    '2151': 'You have converted once today, please come back tomorrow',
    '2152': 'The currency price fluctuates too much, please try again later.',
    '2153': 'The amount of a single conversion shall not exceed 20U',
    '2154': 'System error, please try again later',
    '2155': 'Your account status is abnormal and cannot be converted',
    '2156': 'Advanced Identity Verification needs to be completed first',
    '2157': 'Insufficient balance',
    '2170': 'You have exceeded the daily withdrawal limit. For your safety, please wait 24 hours and try again',
    '2200': 'Please enable your Google/Phone/E-mail Authentication',
    '2203': 'No coin matches',
    '2204': 'The remark is too long',
    '2205': '“Please enter your address memo”',
    '2206': 'Please enter a valid address',
    '2207': 'This address has already existed',
    '2208': 'This address is your deposit address',
    '2209': 'Your address is not available',
    '2211': 'Withdrawal to contract address is not supported',
    '2215': 'Please check your memo',
    '2300': 'No coin matches',
    '2301': 'Withdraw forbidden',
    '2400': 'This file format is not supported',
    '2401': 'The server is busy now. Please try again later',
    '2402': 'Verified sucessfully',
    '2403': 'The server is busy now. Please try again later',
    '2404': 'The server is busy now. Please try again later',
    '2405': 'Please enter a valid ID number',
    '2406': 'This ID number has been used on another account',
    '2410': 'Your account is already in verification and no other new verification is available.',
    '2501': 'Invalid link',
    '2502': 'The link is expired',
    '2690': 'You have enabled 2FA via Google Authenticator',
    '2691': "You haven't bound Google Authenticator ",
    '2701': 'You have already voted 11 times today',
    '2703': "You don't have enough BMX to vote",
    '2704': 'You can only vote at most 11 times a day',
    '2705': 'You have already shared today',
    '2801': 'The investment of this project is closed now',
    '2802': "The project doesn't exist",
    '2803': "You can't invest in this project now",
    '2804': 'Please reduce your amount and try again',
    '2805': 'Insufficient balance',
    '2806': 'Your amount must be a multiple of 100',
    '2807': 'No records',
    '2808': "You can't renew the investment now",
    '3000': 'The server is busy now. Please try again later',
    '3001': 'Too many failed attempts. Please try an hour again later',
    '3002': 'Too many failed attempts. Please try an hour again later',
    '3003': 'Too many failed attempts. Please try an hour again later',
    '3004': 'Too many failed attempts. Please try an hour again later',
    '3005': 'Please contact BitMart customer service to reset your password',
    '3006': 'Too many failed attempts. Please try an hour again later',
    '3007': 'Your account has been temporarily frozen for security concerns. Please try again later',
    '3101': 'You have a API with duplicate memo',
    '3103': 'The size of the trusted IP list should be less than or equal to 10',
    '3104': 'User can create at most 5 APIs',
    '3301': 'You are not entitled to enable this service',
    '3501': 'The server is busy now. Please try again later',
    '3502': 'The server is busy now. Please try again later',
    '4800': 'Insufficient amount, please find another ad.',
    '5113': 'Suspend transfer out',
    '9999': 'The server is busy now. Please try again later',
    '10010': 'You have voted this coin today!',
    '10011': 'You have already voted three coins today!',
    '12201': 'Less than the limit amount',
    '12203': 'The document information is inconsistent with the intermediate verification information. Please re-upload or contact customer service.',
    '12301': 'The account is abnormal. Please contact customer service',
    '12302': 'You have exceeded the current withdrawal limit',
    '12303': 'You have exceeded the number of withdrawals for the day',
    '12304': 'Manual review',
    '12305': "After account security settings' modification， transfer or withdrawal of coin is prohibited within 24 hours",
    '12306': 'Internal Error',
    '12307': 'Enable at least 2 security verifications',
    '12308': 'Withdrawal failed. The withdrawal amount cannot exceed the amount purchased within 24 hours of OTC.',
    '12502': 'The currency is under maintenance, deposit is suspended.',
    '12503': 'You are not allowed to deposit',
    '12504': 'Withdrawal timed out. Please re-initiate withdrawal',
    '12505': 'Amount limit 50-20000 USD.',
    '12506': 'The currency is under maintenance, withdrawal is suspended.',
    '12507': 'You are not allowed to transfer to future account',
    '12508': 'Transfer is abnormal. Please try it later',
    '12509': 'Pls active Future service first',
    '12510': 'Pls active Future service first',
    '12511': 'Pls active Future service first',
    '12512': 'Pls active Future service first',
    '12513': 'Less than the minumun transfer limit',
    '12514': 'You are not allowed to transfer to Buy & Sell account',
    '12515': 'Please complete your personal verification(Starter)',
    '12516': 'Sevices is not available in your countries and areas',
    '12517': 'We will process your transfer request within 12 hours, and the contract transaction will not be affected during this period',
    '12519': 'Transfer Failed. Please close the cross positions in the futures account and try again.',
    '14102': 'Current currency not available',
    '14103': 'Current currency not available',
    '14111': 'Current currency not supported by current channel',
    '14112': 'Channel not exist',
    '14113': 'Channel not available',
    '14114': 'The financial institution is not supported by the current channel',
    '14115': 'The bank is unavailable temporary',
    '14201': 'Fiat identification unverified',
    '14230': 'User unauthorized to deposit in the current channel',
    '14231': 'User unauthorized to withdraw in the current channel',
    '14302': 'Selected bank card not exist',
    '14303': 'Selected bank card not bound. Please delete and rebind',
    '14304': 'The channel associated with the selected card is not available',
    '14305': 'Do not repeat the binding',
    '14306': 'The number of bound accounts exceeds the limit',
    '14310': 'Failed to delete the bank card',
    '14311': 'This account can’t be deleted because a transaction is pending. Please wait for the transaction to complete and then delete the account.',
    '14320': 'Deposit function of selected bank card frozen',
    '14321': 'Withdrawal function of selected bank card frozen',
    '14322': 'Deposit function of selected bank card not enabled',
    '14323': 'Withdrawal function of selected bank card not enabled',
    '14324': 'Selected bank card not verified',
    '14350': 'Session expired. Please re-enter username and password',
    '14351': 'MFA is required to link the bank card',
    '14352': 'Bank card username or password is incorrect',
    '14353': 'Bank login attempt too many times.',
    '14362': 'Binding failed, the number of accounts has exceeded the limit',
    '14363': 'Routing num is incorrect',
    '14371': 'Routing num is incorrect',
    '14372': 'Account num is incorrect',
    '14401': 'Platform account not exist',
    '14500': 'Current service unavailable',
    '14501': 'Deposit/withdrawal amount cannot be empty',
    '14502': 'Deposit/withdrawal amount should be greater than 0',
    '14503': 'Transfer amount less than handling fee',
    '14521': 'Account is temporarily frozen',
    '14522': 'Daily total amount limit',
    '14523': 'Daily frequency limit',
    '14524': 'Large transaction, under review',
    '14531': 'Failed to cancel',
    '14550': 'Failed to generate Order ID',
    '14551': 'Failed to generate wire deposit Order Reference No.',
    '14601': 'Failed to freeze the wallet balance, unable to withdraw',
    '14602': 'Insufficient balance available for wallet withdrawal',
    '16003': 'No deduction is supported',
    '17000': 'Session is closed',
    '17001': 'The quota has been snapped up',
    '17002': 'Activity not started',
    '17003': 'Activity not started',
    '17004': 'The activity is over',
    '17005': 'The activity is over',
    '17006': 'Activity does not exist',
    '17007': 'Less than the minimum purchase quantity',
    '17008': 'Greater than maximum purchase quantity',
    '17009': 'The system is busy, please try again later',
    '17010': 'Do not repurchase',
    '17011': 'The activity is over',
    '17012': 'The system is busy, please try again later',
    '17013': 'The activity is over',
    '17014': 'Please complete your personal verification(Advanced)',
    '17015': 'Sevices is not available in your countries and areas',
    '17999': 'he system is busy, please try again later',
    '18001': 'The file format does not match the requirements',
    '18002': 'The file format does not match the requirements',
    '18003': 'The file is abnormal. Please upload it again',
    '18004': 'The file has exceeded the limit',
    '18005': 'The file cannot be empty',
    '18006': 'The file is abnormal. Please upload it again',
    '20000': 'Activity has not started',
    '20001': 'Operation is too Frequent. Please try again later',
    '20002': 'Operation is too Frequent. Please try again later',
    '20004': 'Insufficient balance',
    '20005': 'Minimum lock amount',
    '20006': 'Exceeded the maximum lock amount',
    '20007': 'Operation is too Frequent. Please try again later',
    '20008': 'This event hasended',
    '20009': 'You are noteligible toparticipate',
    '21201': 'Activity does not exist',
    '21205': 'Activity has not started',
    '21206': 'The event is completed',
    '21252': 'Insufficient balance',
    '21253': 'Lock failed',
    '21254': 'Lock failed',
    '21255': 'The maximum number of lock-able positions is {0}BMX',
    '21256': 'Less than the minimum lock amount',
    '21257': 'Greater than the maximum number of locks',
    '24041': 'Subscription input precision is not legal. Please enter again.',
    '24042': 'Subscription input precision is not legal. Please enter again.',
    '24201': 'Please re-enter the amount.',
    '24211': 'You cannot subscribe now.',
    '24212': 'There is not enough available quota, the available quota is {0}.',
    '24215': 'The precision exceeds the limit. Please re-enter.',
    '24220': 'Your subscription amount should be greater than the minimum limit',
    '24221': 'Your subscription amount exceeds the maximum limit.',
    '24222': 'The subscription is successful. Please do not repeat the operation',
    '24243': 'Your balance is insufficient',
    '25002': 'The coin does not exist. Please switch coin',
    '25003': 'Dear, the current project does not support your region, thanks for your support.',
    '25201': 'The transfer amount cannot be empty or less than or equal to 0',
    '25203': 'Incorrect number of strokes. Please try again',
    '25204': 'The transfer amount cannot be less than {0}USDT',
    '25211': 'Over transferable balance, the transfer failed',
    '25212': 'The transfer failed. Please try again',
    '25213': 'The transfer failed and the service is temporarily unavailable.',
    '25217': 'The account is abnormal, please contact customer service.',
    '25220': 'You are not allowed to open position',
    '25221': 'You are not allowed to transfer to future account',
    '25900': 'Unable to transfer as our copy trading feature does not support institutional accounts at this moment',
    '25901': 'Institutional accounts cannot apply to become a master trader',
    '25903': 'The daily limit for adding sub-affiliates has been reached today',
    '25904': 'The operation is too frequent, please try again later.',
    '27000': 'The event has completed',
    '32051': 'The network fee has expired. Please resubmit your order.',
    '32080': 'Please complete your personal verification(Starter)',
    '32081': 'Please complete your personal verification(Advanced)',
    '32082': 'Please enable your Google/Phone/E-mail Authentication',
    '32083': 'Sevices is not available in your countries and areas',
    '32091': 'You are not allowed to buy',
    '32092': 'You are not allowed to sell',
    '33000': 'System is abnormal. Please try it later',
    '33001': 'You are not allowed to trade',
    '33002': 'System is abnormal. Please try it later',
    '33003': 'System is abnormal. Please try it later',
    '33004': 'System is abnormal. Please try it later',
    '33100': 'System is abnormal. Please try it later',
    '33101': 'System is abnormal. Please try it later',
    '33102': 'Enough not balance',
    '33103': 'Account has been frozen',
    '33104': 'Trading suspended',
    '33105': 'Order shortage parameter',
    '33106': 'The order does not comply with the rules',
    '33107': 'Order has been canceled',
    '33108': 'Order has been filled',
    '33109': 'Order is not exist',
    '33110': 'Partial cancellation of order failed',
    '33111': 'Trading suspended',
    '33112': 'The buy order price cannot be higher than the open price',
    '33113': 'The sell order price cannot be lower than the open price',
    '33114': 'Trading not started',
    '33115': 'Please complete your personal verification(Advanced)',
    '33116': 'Sevices is not available in your countries and areas',
    '33117': 'The quote price is too high to find matched depth',
    '33118': 'The quote price is too low to find matched depth',
    '33119': 'cancel failed, ioc order is not allowed to cancel',
    '33121': 'Sorry, the status of your account is over-loss, you are prohibited from placing margin orders.',
    '33124': 'size ≥ {0}',
    '33125': 'price ≥ {0}',
    '33126': 'size * price ≥ {0}',
    '33127': 'notional ≥ {0}',
    '33128': 'notional is too small',
    '33129': 'size ≥ {0}',
    '33130': 'size is too small',
    '33134': 'No permission for this pair',
    '33135': 'Your account has passed KYC-0, please complete KYC-1 first',
    '33136': 'Your account has passed KYC-1, please complete KYC-2 first',
    '33137': 'The NFT trading function is not available in your country or area, please contact customer service if you have any questions.',
    '33138': 'need QR code',
    '33144': 'This pair is abnormal or will be delist，suspend trading/borrowing/transfer.',
    '34001': 'Product does not exist',
    '34002': 'Insufficient balance',
    '34003': 'Wrong order amount',
    '34004': 'Insufficient product subscription quota',
    '34005': 'Unavailable to subscribe or redeem during 00: 00 to 00: 15 UTC + 4',
    '34006': 'User cumulative subscription exceed the limit',
    '34008': 'You are not allowed to subscribe',
    '34009': 'You are not allowed to redeem',
    '34011': 'Sale stop',
    '34015': 'Please complete your personal verification(Advanced)',
    '34016': 'Sevices is not available in your countries and areas',
    '34017': 'User’s country is forbidden for BitMart Earn.',
    '34057': 'The product you subscribed for is sold out/Stopped Sell, you can choose another product to re-initiate your application.',
    '34059': 'This order cannot be redeemed in advance, since you participated in the event',
    '34100': 'System is busy now, please try again later',
    '34101': 'System is busy now, please try again later',
    '34102': 'Sorry, you did not participate.',
    '34103': 'You have already participated. Please do not participate again.',
    '34104': 'Exceeds the maximum number of ticket',
    '34105': 'Insufficient available assests',
    '34106': 'There are currently too many visitors, please try again later. You can participate during the participation period.',
    '34107': 'System is busy now, please try again later',
    '34108': 'System is busy now, please try again later',
    '34109': 'The participation period has not started yet.',
    '34110': 'There are currently too many visitors. Please try again later. You can participate during the participation period.',
    '34111': 'Only users who complete KYC are qualified to participate.',
    '34112': 'Sorry, you are not eligible for participation.',
    '34113': 'Please input your ticket number.',
    '34114': 'The minimum number of tickets is 1.',
    '34115': 'Sorry, you are not eligible for participation.',
    '35507': 'Your transfer request is being processed, please kindly wait, thanks.',
    '35511': 'You have unclosed positions or pending orders, please clear them before open credit-line service.',
    '36000': 'Request parameter exception',
    '36001': 'Insert exception',
    '36002': 'Update exception',
    '36003': 'Query exception',
    '36004': 'Delete exception',
    '36005': 'Upload exception',
    '36006': 'Upload file is empty',
    '36007': 'Upload file format error',
    '36008': 'Status is error',
    '36009': 'Order status is error',
    '36010': 'Upload file too large',
    '36020': 'User information is incorrect, please contact customer service if you have any questions.',
    '36021': 'This creator does not exist',
    '36022': 'This collectible does not exist',
    '36023': 'This nft does not exist',
    '36024': 'This show nft does not exist',
    '36025': 'This storage info does not exist',
    '36026': 'This order does not exist',
    '36027': 'This collectible does not bind creator',
    '36028': 'This airdrop does not exist',
    '36030': 'This id does not exist',
    '36031': 'This status is not storage',
    '36032': 'This status is not on sale',
    '36033': 'lack inventory',
    '36034': 'create order error',
    '36035': 'request feign fail',
    '36036': 'get userInfo error',
    '36037': 'not purchasable timing',
    '36038': 'NFT has sold',
    '36039': 'Login name is not correct',
    '36040': 'sale time is error',
    '36041': 'not has NFT',
    '36042': 'You have insufficient balance in your Spot Account. Please confirm your account status.',
    '36043': 'have no coin info',
    '36044': 'system config not init or unknown network',
    '36045': 'Risk operation,please try it again.',
    '36046': 'account refund fail',
    '36047': 'NFT withdrawals fail, please contact customer service if you have any questions. ',
    '36048': 'check gas fail',
    '36049': 'NFT withdrawal fee has changed, please retry.',
    '36050': 'exist nft is not this user',
    '36051': 'http request fail',
    '36052': 'do deduct fail',
    '36053': 'The wallet is frozen,please check it.',
    '36054': 'get dollar rate error',
    '36055': 'Unlock nft or create order error',
    '36061': 'query nft does not exist',
    '36062': 'query chain nft has error',
    '36063': 'has nftTokenId does not exist',
    '36064': 'the nft status has been changed',
    '36065': 'Risk operation,please try it in safe environment .',
    '36066': 'System error,please try it again',
    '36067': 'The blockchain is busy,please try it again',
    '36068': 'NFT code is null',
    '36069': 'Incorrect purchase, you are the owner of this item',
    '36070': 'excel export error',
    '36071': 'quantity not same',
    '36072': "airdrop task's status is not executable",
    '36073': 'no airdrop detail',
    '36074': 'airdrop check error,please check the fail reason',
    '36075': 'airdrop execute fail',
    '36076': 'IO exception',
    '36077': 'enum does not exist.',
    '36080': 'The NFT buying function is not available for this NFT item, please contact customer service if you have any questions.',
    '36081': 'The NFT listing function is not available for this NFT item, please contact customer service if you have any questions.',
    '36082': 'The NFT deposit function is not available for this NFT item, please contact customer service if you have any questions.',
    '36083': 'The NFT withdrawal function is not available for this NFT item, please contact customer service if you have any questions.',
    '36090': 'Account has been frozen , pls contact with us.',
    '36091': 'Your NFT withdrawals is now unavailable, please contact customer service if you have any questions.',
    '36092': 'Your NFT deposit function is now unavailable, please contact customer service if you have any questions.',
    '36093': 'Your NFT trading function is now unavailable, please contact customer service if you have any questions.',
    '36094': 'Your NFT listing function is now unavailable, please contact customer service if you have any questions.',
    '36095': 'Listing nft fail',
    '36096': 'The number of NFTs is incorrect, please contact customer service if you have any questions.',
    '36097': 'You have insufficient balance in your NFT Account. Please confirm your account status.',
    '36098': 'Delisting nft fail',
    '36100': 'This nft item does not exist',
    '36101': 'purchase nft database error',
    '36102': 'item data error',
    '36110': 'upload result error.',
    '36111': 'nft upload un done',
    '36112': 'order type is wrong',
    '36113': 'can not find deposit address',
    '36114': 'Please try later, the metadata is updating now.',
    '36117': 'token uri is null. ',
    '36118': 'nft not set price',
    '36120': 'Your account has not passed KYC, please complete KYC first.',
    '36121': 'This collectible is not online',
    '36122': 'send message error',
    '36123': 'transfer NFT error',
    '36124': 'You have reached the purchase limit for the collection',
    '36125': 'transfer user error',
    '36126': 'This item has order don`t finish',
    '36127': 'Please try later, frequent commit. ',
    '36128': 'collectible error. ',
    '36129': 'price error. ',
    '36130': 'The NFT trading function is not available in your country or area, please contact customer service if you have any questions.',
    '36131': 'Please complete the identity verification Level 2 to ensure the account security, due to the large amount of transactions.',
    '36132': 'Server is crowded,please try later.',
    '36133': 'has NFT is trading',
    '36134': 'nft list price must not be greater than 100, 000 usd.',
    '40001': 'Request Failed',
    '40002': 'Up to 5 deposit addresses can be generated.',
    '40011': 'The modification status is incorrect and cannot be modified',
    '40012': 'Invalid parameter',
    '40013': 'Invalid signature',
    '40014': 'Invitation ID is invalid',
    '40015': 'Invited ID is invalid',
    '40016': 'Invalid commission rate',
    '40017': 'The invitee has become a partner already',
    '40018': 'Invalid verification code',
    '40019': 'AES encryption failed',
    '40020': 'Unable to retrieve user trading data',
    '40021': 'Time format conversion failed',
    '40022': 'http request failed',
    '40023': 'Administrator ID cannot be null',
    '40024': 'Unable to analysis the value',
    '40025': 'Invalid User ID',
    '40026': 'Invalid Administrator ID',
    '40027': 'Frequent requests, please try again later',
    '40040': 'type is null',
    '40043': 'Query userid is a required parameter',
    '40044': 'Query contractid is a required parameter',
    '41103': 'This currency cannot be borrowed',
    '41323': 'Credit funds cannot be used for collateral',
    '41324': 'Asset transfer in progress, please try again later',
    '41325': 'This currency cannot be used as collateral',
    '41326': 'Collateral cannot be increased for this currency',
    '46001': 'Due to server capacity constraints, each user can generate up to 5 times per month.',
    '48101': 'This ad is inactive now, please find another ad.',
    '48104': 'Insufficient amount, please find anohter ad.',
    '48212': 'Already remind the counterparty, please try later',
    '48216': 'Cannot place an order for your own ads.',
    '48226': 'You have an ongoing order with this advertiser, please finish the exisiting order first.',
    '50001': 'apply Fail',
    '50002': 'Partner application data does not exist',
    '50004': 'BD already exists',
    '50005': 'BD does not exist',
    '50006': 'Please relocate partners before remove',
    '50007': 'No partner exists under you',
    '50008': 'The partner does not exist',
    '50009': 'Unable to review repeatedly',
    '50010': 'You have been already a partner',
    '50011': 'BD is unable to proceed the partner application',
    '50012': 'Not qualified to be a BD',
    '50013': 'Mail delivery failed',
    '52001': 'Size of trustIpList should be less than or equal to 10',
    '52002': 'User could create at most 10 APIs',
    '52009': 'Sub-account not found',
    '52010': 'Not your sub-account',
    '52011': 'Repeat request',
    '52012': 'This account has been risk controlled',
    '53002': 'Please complete your personal verification(Advanced)',
    '60023': 'Please complete your personal verification(Starter)',
    '60024': 'Sevices is not available in your countries and areas',
    '60025': 'Please enable your Google/Phone/E-mail Authentication',
    '61008': 'Suspend transfer out',
    '133000': 'Professional users can not enjoy BMX discounts',
    '133001': 'Special users can not enjoy BMX discounts',
    '190001': 'No currency exists',
    '190002': 'This currency is not trading',
    '191001': 'Currency prices are not available',
    '193001': 'Verfication unsuccessful',
    '193002': 'Failed to obtain authentication information',
    '194001': 'The currency cannot be empty',
    '194002': 'The price cannot be empty',
    '194003': 'The amount cannot be empty',
    '194004': '/',
    '194005': 'The uid cannot be empty',
    '194006': 'Beyond maximum accuracy',
    '194007': 'Exceed maximum limit',
    '194008': 'Less than minimum limit',
    '194009': 'Service temporarily unavailable.',
    '194010': 'Amount exceeds limit.',
    '194101': 'Order does not exist',
    '194102': 'Trading confirmed',
    '194103': 'The exchange rate has changed. Please place a new order',
    '194104': 'Trading failure',
    '194105': 'Platform account balance is insufficient, temporarily can not carry out trading',
    '194106': 'Insufficient balance. Please enter again',
    '194107': 'Trading in progress',
    '194108': 'The exchange rate has changed. Please place a new order',
    '194109': 'Please select a payment method',
    '194110': 'Payment does not exist',
    '194111': 'Current payment method is not supported',
    '33139_deprecated': 'The maximum order leverage for credit is 1x'
}