export const enRes = {
	"e_-2200": "User needs to bind Google authenticator or phone to change address.",
	"e_-2203": "Coin does not exist",
	"e_-2204": "Request too long",
	"e_-2205": "Memo is empty",
	"e_-2206": "Invalid address",
	"e_-2215": "Please check your memo",
	"e_-2207": "Address already exists",
	"e_-2208": "Address can not be updated",
	"e_-2209": "Address does not exist",
	"e_-2210": "This currency withdrawal is suspended",
	"e_-2103": "Minimum withdraw count %s",
	"e_-2105": "Balance not enough",
	"e_-2106": "Unsupported operation",
	"e_-2107": "Exceed daily withdrawal quota, for your safety, please wait 24 hours and try again",
	"e_-2109": "please check The Email /Phone number/BitMart ID And try again",
	"e_-2110": "can not get user info, please try again",
	"e_-2111": "Monitor that the withdrawal will cause the overall spot wallet to fall below the Margin call risk rate. Please revise the withdrawal amount as appropriate.",
	"e_-2112": "Sub-account does not support withdraw",
	"e_-2113": "Missing authentication name",
	"e_-2114": "Sub-account does not support deposit",
	"e_-2115": "Please complete your institution verification to enable withdrawal function.",
	"e_-2116": "Deposit amount should be within {0.000001}-{0.1}",
	"e_-2117": "Saving BTC-lightning invoice is not supported.",
	"e_-2118": "Failed to get invoice fee",
	"e_-2119": "The input amount does not match the parsed amount",
	"e_-2121": "Invoice is invalid",
	"e_-2122": "Invoice has expired, please re-create",
	"e_-2123": "This network not support domain address",
	"e_-2124": "Domain is invalid",
	"e_-2125": "Given you have deposited crypto through P2P trading within 24 hours, the equivalent value of the deposit( %s USDT) can not be withdrawaled in %s hours.",
	"e_-2126": "Withdrawal amount must be an integer multiple of %s",
	"e_-2150": "Your account does not support Convert",
	"e_-2151": "You have converted once today, please come back tomorrow",
	"e_-2152": "The currency price fluctuates too much, please try again later.",
	"e_-2153": "The amount of a single conversion shall not exceed 20U",
	"e_-2154": "System error, please try again later",
	"e_-2155": "Your account status is abnormal and cannot be converted",
	"e_-2156": "Advanced Identity Verification needs to be completed first",
	"e_-2157": "Insufficient balance",
	"e_-2211": "Query withdraw fee error",
	"e_-2212": "Create withdraw fee token error",
	"e_-2250": "Credit Account not found",
	"e_-2251": "The current user has no credit pledge assets",
	"e_-2252": "There is no credit pledge asset in the current currency",
	"e_-2253": "Insufficient account balance",
	"e_-1005": "Account is frozen due to security policies. Please contact customer service.",
	"e_-2300": "No matching coin",
	"e_-2301": "Withdraw forbidden",
	"e_-2302": " internal Withdraw forbidden",
	"e_3014": "The withdrawal user and the target user cannot be the same",
	"e_-5100": "Account unavailable, disabled in background",
	"e_-5101": "No matching coin",
	"e_-5102": "Asset transfer between accounts is not available,permission closed by main account or background",
	"e_-5103": "Can't transfer to oneself",
	"e_-5104": "Sub account does not have permission",
	"e_-5105": "Can't find source account",
	"e_-5106": "Can't find target account",
	"e_-5107": "Unsupported transfer type",
	"e_-5108": "Only support sub-account",
	"e_-5109": "Unsupported transfer type",
	"e_-5111": "Account unavailable, Frozen by main account",
	"e_-5112": "The sub-account function only supports organization accounts",
	"e_-5113": "Suspend transfer out",
	"e_-35600": "This coin is suspend transfer.",
	"e_-35601": "This account is restricted from Margin transfer.",
	"e_-35602": "Margin account not opened.",
	"e_-35603": "This pair will be delisted from Isolated Margin. Suspend transfer.",
	"e_12501": "currency does not exist",
	"e_12518": "The transfer function is under maintenance, please try again later.",
	"e_12520": "Your account has not yet completed the kyc advanced certification, please complete first",
	"e_32000": "Request parameter exception",
	"e_32001": "Parameter verification failed",
	"e_32002": "Our Buy & Sell module is temporarily unavailable due to system maintenance. We apologize for any inconvenience this may cause.",
	"e_32003": "Buy & Sell is under maintenance.",
	"e_32004": "Does not support current digital currency.",
	"e_32005": "Does not support current fiat currency.",
	"e_32010": "The current currency does not support recharge",
	"e_32011": "Unable to get the digital currency recharge address",
	"e_32012": "Order creation failed",
	"e_32013": "Order payment status update failed",
	"e_32014": "Transaction failed. Please consider increasing the purchase amount or using a different service provider",
	"e_32015": "Failed to initiate a currency sale transaction",
	"e_32016": "User registration time does not exist",
	"e_32017": "Does not support the current payment channel",
	"e_32018": "Failed to create MoonPay payment link",
	"e_32019": "Failed to query MoonPay purchase order",
	"e_32020": "This user does not exist",
	"e_32023": "Failed to query the limit on the number of digital currencies sold",
	"e_32024": "Failed to create MoonPay sell currency link",
	"e_32025": "Failed to send encrypted currency, the current operation is not supported.",
	"e_32026": "Failed to query the total number of digital currency orders.",
	"e_32027": "Failed to query the detail of digital currency orders.",
	"e_32028": "Failed to query currency information.",
	"e_32029": "Failed to access service provider, please refresh the page.",
	"e_32030": "Failed to query user info.",
	"e_32031": "Failed to query sdk param.",
	"e_32032": "interface version does not support.",
	"e_32050": "Query network fee failed.",
	"e_32052": "Query withdraw day quota failed.",
	"e_32053": "Query coin rate failed.",
	"e_32054": "The user's cash withdrawal exceeds the daily limit.",
	"e_32055": "The user's cash withdrawal amount is less than the withdrawal fee.",
	"e_32056": "The user's cash withdrawal amount is less than minimum withdrawal amount.",
	"e_32084": "Please complete your institution verification to enable withdrawal function.",
	"e_32100": "Failed to query the list of legal currencies supported by moonpay",
	"e_32101": "Failed to query the list of digital currencies supported by moonpay",
	"e_32102": "Failed to query moonpay to purchase digital currency quotation",
	"e_32103": "Failed to query moonpay's digital currency quotation",
	"e_32104": "The buy transaction of MoonPay is cancelled",
	"e_32106": "Failed to update order information based on moonpay feedback",
	"e_32107": "Failed to query the quotation of digital currency purchase by simplex",
	"e_32108": "Failed to query the quotation of digital currency sold by simplex",
	"e_32109": "Failed to send digital currency purchase request to simplex",
	"e_32110": "Failed to send request to sell digital currency to simplex",
	"e_32211": "Parameter signature error",
	"e_32212": "Access token get fail",
	"e_32200": "Failed to obtain the balance of the specified currency in the user's specified account",
	"e_32201": "Failed to freeze user account assets",
	"e_32112": "The current virtual currency deposit is closed",
	"e_32113": "The current virtual currency does not exist",
	"e_32114": "Virtual currency configuration information is abnormal and cannot be traded",
	"e_32115": "The user account balance is insufficient and the operation failed.",
	"e_32116": "Withdrawal request parameter verification failed",
	"e_32117": "The order has been withdrawn, and the corresponding serial id cannot be found",
	"e_32118": "The withdrawal amount is less than the minimum withdrawal amount",
	"e_32119": "User's fiat currency account wallet freeze failed",
	"e_32120": "Network error, failed to send withdrawal request",
	"e_32121": "Failed to verify the parameters of the request to obtain the transaction id on the chain",
	"e_32122": "Network error, failed to query transaction information after the virtual currency was on the chain",
	"e_32123": "Failed to update the withdrawal address in the token sale order",
	"e_32124": "Failed to update the withdrawal id in the legal currency withdrawal order",
	"e_32125": "Failed to update the local processing status in the legal currency withdrawal order",
	"e_32126": "Failed to update the withdrawal quantity in the legal currency withdrawal order",
	"e_32202": "Unfreeze and return user account assets failed",
	"e_32203": "Deduction of user account assets failed",
	"e_32900": "Network error",
	"e_32901": "Network error, http call error",
	"e_32902": "Network error, Grpc call error",
	"e_32800": "Fiat biz switch update failed",
	"e_32801": "Channel coin is empty",
	"e_32802": "Channel currency is associated"
}