module.exports ={
  "e_0": "Success",
  "e_10": "Critical business exception",
  "e_12307": "Please enable at least two security verifications.",
  "e_1706": "Invalid username",
  "e_1704": "Login passwords are the same",
  "e_1702": "Wrong original login password",
  "e_3504": "scyToken error",
  "e_3503": "mfaToken error",
  "e_3501": "gwToken error",
  "e_1112": "Account already registered",
  "e_1108": "Wrong invitation code",
  "e_1106": "Invalid email address",
  "e_1103": "Invalid phone number",
  "e_1006": "Account is disabled, please contact the main account",
  "e_1008": "User not exists",
  "e_1009": "The financial account is not allowed to log in to the web/app station.",
  "e_1010": "Your phone already bound",
  "e_1011": "This Phone already bound",
  "e_1012": "Your phone not bound",
  "e_1015": "Your mail not bound",
  "e_1016": "Google authenticator not bound",
  "e_1018": "Google authenticator reload",
  "e_1013": "Your mail already bound",
  "e_1014": "This Mail already bound",
  "e_1017": "Google authenticator already bound",
  "e_1023": "Not support account",
  "e_1029": "user has invited people",
  "e_1030": "Not support invite no",
  "e_1031": "invite code does exist",
  "e_1033": "invite code size limit exceed",
  "e_1005": "Account is frozen due to security policies. Please contact customer service.",
  "e_1002": "Invalid username or password, you have %d chances to retry",
  "e_1070": "client id not found",
  "e_3008": "The account is abnormal, please try again later",
  "e_1091": "The main account is unavailable.",
  "e_3004": "Account is frozen due to security policies, please try again after %d hours",
  "e_3003": "Account is frozen due to security policies, please try again after %d hours",
  "e_3002": "Account is frozen due to security policies, please try again after %d hours",
  "e_3001": "Account is frozen due to security policies, please try again after %d hours",
  "e_1092": "Institutional KYC verification not passed.",
  "e_1093": "Sub-account creation limit reached.",
  "e_1094": "Your account has been cancelled",
  "e_1095": "Your account type does not support cancel",
  "e_1101": "Copy string literal text to the clipboard",
  "e_1500": "Header X-BM-CLIENT invalid",
  "e_1501": "Header X-BM-MERCHANT-CLIENT-ID is empty",
  "e_1502": "Header X-BM-MERCHANT-SIGN is empty",
  "e_1503": "Header X-BM-MERCHANT-TIMESTAMP is empty",
  "e_1505": "authorize code invalid",
  "e_1506": "You have submitted too many times, please try again tomorrow",
  "e_2410": "kyc information does not exist",
  "e_1721": "underage",
  "e_1725": "invalid kyc status",
  "e_1726": "Not you sub account",
  "e_1727": "Sub account not allow login app",
  "e_1728": "No permission, please contact our administrator",
  "e_1732": "Invalid Information",
  "e_1733": "Invalid Country/Region",
  "e_1734": "Invalid Birthday",
  "e_1736": "Sorry, only letters(a-z), numbers(0-9), and periods(.), character(! # $ % * / ? ^ + - ` { | } ~ _) are allowed.",
  "e_1737": "Sorry, the character needs to be less than 32 characters.",
  "e_1738": "Sorry, please enter your valid email.",
  "e_1739": "You Haven't Certified Institutional KYC",
  "e_1740": "Your Application Is Pending Or Approved",
  "e_1741": "Your Apply Is Auditing Or Passed",
  "e_1742": "Your Apply Save Error",
  "e_1743": "Invite Relation Error",
  "e_1744": "Cashback Is Greater Than Agent Rebate",
  "e_1745": "Primary certification is required",
  "e_1750": "kyc level does not meet",
  "e_1751": "please check your name",
  "e_1752": "Please check your name (English)",
  "e_1753": "Submission is not supported in authentication.",
  "e_1754": "Special users cannot submit authentication.",
  "e_1755": "Internal users cannot apply for institutional certification.",
  "e_1756": "Sub account denied",
  "e_1757": "BitMart service is not available for the selected area.",
  "e_1758": "The BitMart.HK account and BitMart account are not interchangeable.",
  "e_1759": "Agent already exist",
  "e_1760": "System is abnormal, please try it later",
  "e_1763": "IP is not in the whitelist.",
  "e_1764": "Not mm-bot is forbidden to log in",
  "e_46": "Account not found",
  "e_40": "Request expired",
  "e_36": "Forbidden",
  "e_34": "Missing verification code",
  "e_31": "Network busy, please refresh the page",
  "e_30": "Visit too often, please try again later",
  "e_23": "login code expired",
  "e_18": "Wrong login password，you have %d chances to retry",
  "e_14": "Invalid email verification code，you have %d chances to retry",
  "e_13": "Invalid SMS verification code, you have %d chances to retry",
  "e_12": "Invalid Google verification code，you have %d chances to retry",
  "e_9": "Wrong email verification code",
  "e_8": "Wrong SMS verification code",
  "e_7": "Wrong captcha",
  "e_6": "User not login",
  "e_5": "Duplicate request",
  "e_4": "Network error",
  "e_3": "Invalid request",
  "e_2": "Login too often, please try again after 2 hours",
  "e_1": "Failure",
  "e_341036": "database err",
  "e_34100": "activity not find",
  "e_34101": "award not find",
  "e_34102": "user not join",
  "e_34103": "user has join",
  "e_34104": "over max ticket num",
  "e_34105": "balance not enough",
  "e_34107": "price coin not find",
  "e_34108": "cal snapshotBalance err",
  "e_34110": "your request is processing now, please wait",
  "e_34115": "no qualification",
  "e_34116": "Please open the contract",
  "e_34117": "Please try later.",
  "e_34135": "Your account has passed KYC-0, please complete KYC-1 first",
  "e_34136": "Your account has passed KYC-1, please complete KYC-2 first",
  "e_34138": "need QR code",
  "e_34140": "The function is not available in your country or area, please contact customer service if you have any questions.",
  "e_66000": "param error.",
  "e_66001": "The daily volume of is less than 10% of the available amount.",
  "e_66002": "IP is not in the whitelist",
  "e_66003": "user not authorized.",
  "e_66004": "api authorized error.",
  "e_66005": "mmbot user exists.",
  "e_66006": "user not exists.",
  "e_66007": "api key is not bound.",
  "e_66008": "api verify error.",
  "e_66009": "The quantity of each order should be between %s.",
  "e_33135": "Please complete your personal verification(Starter)",
  "e_33136": "Please complete your personal verification(Advanced)",
  "e_33137": "Services is not available in your countries and areas",
  "e_33138": "Your account has not yet completed the qr code certification, please complete first",
  "e_36003": "Query exception",
  "e_36009": "Order status is error",
  "e_36020": "This user does not exist",
  "e_36022": "This collectible does not exist",
  "e_36023": "This nft does not exist",
  "e_36026": "This order does not exist",
  "e_36032": "This status is not on sale",
  "e_36033": "lack inventory",
  "e_36034": "create order error",
  "e_36035": "request feign fail",
  "e_36036": "get userInfo error",
  "e_36037": "not purchasable timing",
  "e_36038": "NFT has sold",
  "e_36041": "not has NFT",
  "e_36042": "account is not enough",
  "e_36043": "have no coin info",
  "e_36045": "Risk operation,please try it again.",
  "e_36046": "account refund fail",
  "e_36044": "system config not init or unknown network",
  "e_36047": "nft withdraw fail",
  "e_36049": "withdraw fee changed",
  "e_36050": "exist nft is not this user",
  "e_36053": "The wallet is frozen,please check it.",
  "e_36054": "get dollar rate error",
  "e_36061": "query nft does not exist",
  "e_36065": "Risk operation,please try it in safe environment .",
  "e_36069": "Incorrect purchase, you are the owner of this item",
  "e_36080": "Sorry, the NFT item can’t be purchased.",
  "e_36081": "Sorry, the NFT item can’t be listed.",
  "e_36082": "Sorry, you can’t deposit the NFT item.",
  "e_36083": "Sorry, This NFT collection does not support withdrawal.",
  "e_36090": "Account has been frozen , please contact with us.",
  "e_36091": "Withdraw prohibited, please contact with us.",
  "e_36092": "Deposit prohibited, please contact with us.",
  "e_36093": "Trading prohibited, please contact with us.",
  "e_36094": "Listing prohibited, please contact with us.",
  "e_36095": "Listing nft fail",
  "e_36096": "subtract nft quality fail",
  "e_36097": "NFT quality is not enough",
  "e_36098": "DeListing nft fail",
  "e_36100": "This nft item does not exist",
  "e_36101": "purchase nft database error",
  "e_36102": "item data error",
  "e_36118": "nft not set price",
  "e_36121": "This collectible is not online",
  "e_36124": "You have reached the purchase limit for the collection.",
  "e_36127": "Please try later, frequent commit.",
  "e_36133": "has NFT is trading",
  "e_36134": "nft list price must not be greater than %s usd.",
  "e_36137": "The operation is frequent. Please try again later.",
  "e_47000": "Contract future activity submit error",
  "e_47001": "Invalid team join code",
  "e_47002": "Concurrent join team failed",
  "e_47003": "Not in sign up time",
  "e_47004": "User is team leader",
  "e_47005": "User has joined team",
  "e_47006": "User contract balance not enough",
  "e_47007": "User risk check failed",
  "e_47008": "Team name exist",
  "e_47009": "Team code exist",
  "e_60": "Partial success",
  "e_NaN": "Success",
  "e_35": "Service unavailable",
  "e_2001": "Select record error",
  "e_2000": "No record",
  "e_3202": "Invalid type",
  "e_3201": "Invalid coinType",
  "e_37": "Force update",
  "e_33": "Invalid signature",
  "e_39000": "PARAM_NOT_EMPTY",
  "e_39100": "SYSTEM_ERROR",
  "e_39101": "BIZ_SOURCE_NOT_EXIST",
  "e_39102": "BIZ_TYPE_NOT_EXIST",
  "e_39103": "USER_BENEFIT_EXIST_DUPLICATE",
  "e_39104": "USER_BENEFIT_GRANTING",
  "e_39105": "BENEFIT_VALUE_TYPE_NOT_EXIST",
  "e_39107": "USER_BENEFIT_STATUS_NOT_EXIST",
  "e_39108": "USER_BENEFIT_STATUS_ERROR",
  "e_39109": "USER_BENEFIT_VERIFY_NUM_NOT_ENOUGH",
  "e_39110": "USER_BENEFIT_SOURCE_NUM_NOT_ENOUGH",
  "e_39111": "USER_BENEFIT_VERIFY_ORDER_STATUS_ERROR",
  "e_39112": "USER_BENEFIT_NOT_EXIST",
  "e_39113": "USER_BENEFIT_FREEZING",
  "e_39114": "USER_BENEFIT_PROVING",
  "e_39117": "USER_BENEFIT_GRANT_FAIL",
  "e_39118": "USER_BENEFIT_RECYCLE_NUM_NOT_ENOUGH",
  "e_39119": "USER_BENEFIT_NFT_BLIND_BOX_NOT_SUPPORT",
  "e_39120": "USER_BENEFIT_SPOT_COIN_PROCESSING",
  "e_39121": "PARAM_VALUE_NOT_EXIST",
  "e_39122": "USER_BENEFIT_VERIFY_ORDER_EXIST",
  "e_39129": "AMOUNT_MUST_MORE_THAN_ZERO",
  "e_39130": "BENEFIT_GRANT_CID_REPEAT",
  "e_39131": "BENEFIT_FREEZE_CALCULATE_ERROR",
  "e_39132": "BENEFIT_EXPORT_ERROR",
  "e_39123": "BENEFIT_NOT_EXIST",
  "e_39124": "BENEFIT_GRANT_MORE_THAN_NUMBER",
  "e_39125": "BENEFIT_NAME_DUPLICATE",
  "e_39126": "BENEFIT_GRANT_CID_NOT_EXIST",
  "e_39127": "PARAM_LENGTH_ERROR",
  "e_39128": "PARAM_NOT_EXIST",
  "e_39133": "USER_BENEFIT_GRANT_ORDER_EXIST",
  "e_39115": "USER_BENEFIT_RECYCLING",
  "e_39116": "USER_BENEFIT_REFUNDING",
  "e_33001": "Your account is frozen due to security policies. Please contact customer service",
  "e_33002": "Method Not Allowed",
  "e_33000": "Bad Request",
  "e_33003": "Unsupported Media Type",
  "e_33004": "Internal Server Error",
  "e_33100": "User account not found",
  "e_33101": "Symbol not found",
  "e_33102": "Balance not enough",
  "e_33103": "User stop trading",
  "e_33104": "This Symbol is stop trading",
  "e_33105": "REQUEST_PARAM_MISS",
  "e_33106": "REQUEST_PARAM_NOT_MATCH",
  "e_33107": "Order is already canceled",
  "e_33108": "Order is already completed",
  "e_33109": "Order does not exist",
  "e_33110": "Orders is canceled partially",
  "e_33111": "Symbol not used",
  "e_33114": "Service unavailable",
  "e_33112": "The buy order price cannot be higher than the open price",
  "e_33115": "kyc invalid level, you need to verify kyc level2",
  "e_33118": "The price is low and there is no matching depth",
  "e_33119": "cancel failed, order is not revocable status",
  "e_33116": "kyc invalid country, services are not available",
  "e_33117": "The price is high and there is no matching depth",
  "e_33113": "The sell order price cannot be lower than the open price",
  "e_33120": "No permission, please contact the main account",
  "e_33121": "Account restricted",
  "e_33122": "This trading pair is not available to trade in your region",
  "e_33123": "Network timeout, please try again",
  "e_33124": "SIZE_NOT_MATCH",
  "e_33125": "PRICE_NOT_MATCH",
  "e_33126": "SIZE_MUL_PRICE_NOT_MATCH",
  "e_33127": "NOTIONAL_NOT_MATCH",
  "e_33128": "NOTIONAL_IS_SMALL",
  "e_33129": "SIZE_IS_SMALL",
  "e_33130": "orderModeCode not match",
  "e_33131": "subOrderModeCode not match",
  "e_33132": "Operation is limited, please try again later",
  "e_33133": "The number of orders exceeds the maximum limit",
  "e_33134": "No permission for this pair",
  "e_33139": "Insufficient balance or frozen amount",
  "e_33140": "Quantity is too small",
  "e_33141": "Trading order failure",
  "e_33142": "Loan success,but trading order failure",
  "e_33143": "Insufficient loan amount",
  "e_33144": "This pair is abnormal or will be delist，suspend trading/borrowing/transfer",
  "e_33145": "Borrowing of this currency has been suspended",
  "e_33146": "This account is restricted from borrowing",
  "e_33147": "This sub-account does not belong to the current main account",
  "e_34019": "The system has received your request and will inform you later by SMS or email",
  "e_34044": "coin's name not match",
  "e_34048": "Org recharge balanced check",
  "e_34040": "Org recharge failed",
  "e_34037": "This order status cannot be withdrawn",
  "e_34021": "the subscribe amount should be greater than order min amount",
  "e_34061": "can not advance redeem",
  "e_34051": "The address of the currency is not configured",
  "e_34042": "The network is unstable, please try again later",
  "e_34041": "Org withdraw failed",
  "e_34018": "need update app",
  "e_34027": "LoginNameList account does not exist",
  "e_34050": "Org withdraw abnormal order timeout 60 second",
  "e_34014": "Institutional users are not allowed to subscribe",
  "e_34047": "Org recharge amount check",
  "e_34049": "Auto subscribe product not exist",
  "e_34045": "机构充提中超过4小时",
  "e_34000": "System exception",
  "e_34052": "This currency does not support withdrawal",
  "e_34060": "Order has advance redeem",
  "e_34022": "the subscribe amount should be less than order max amount",
  "e_34026": "LoginNameList length should be less than 100",
  "e_34039": "Org withdraw address is blank",
  "e_34046": "Org recharge or withdrawal result error more than 4 hours",
  "e_34043": "Order does not exist",
  "e_34036": "The order status cannot be recharged",
  "e_53029": "Receive Failed. Please contact customer service.",
  "e_53000": "System exception",
  "e_53027": "Risk check not pass",
  "e_53012": "The gift is only for the specific user",
  "e_53024": "Creation parameter error",
  "e_53005": "Exceeded the daily maximum amount limit",
  "e_53008": "The password is invalid",
  "e_53003": "Less than the minimum amount",
  "e_53025": "The specified user is empty",
  "e_53016": "No password",
  "e_53009": "The gift is all received",
  "e_53019": "The crypto gift is received repeatedly",
  "e_53010": "The gift is only for the sender's referral",
  "e_53020": "The crypto gift receive failed",
  "e_53001": "Insufficient balance",
  "e_53026": "The specified user is empty",
  "e_53014": "You can only receive one new user crypto gift",
  "e_53028": "The operation is too frequent, please try again later.",
  "e_53011": "The gift is expired",
  "e_53023": "The recipient user does not exist",
  "e_53018": "Failed to cache the crypto gift to redis",
  "e_53006": "No such crypto gift type",
  "e_53013": "The gift is only for the new register user",
  "e_53015": "Password generation failed",
  "e_53022": "Coin exchange rate not found",
  "e_53017": "The crypto gift does not exist",
  "e_53030": "No permission to create",
  "e_53021": "No such user type",
  "e_53007": "This user is not found",
  "e_53004": "Exceeded the maximum amount limit",
  "e_37109": "sorry , this activity you can't join",
  "e_37103": "user has into activity",
  "e_37105": "activity is over",
  "e_37002": "Mission not start",
  "e_37102": "activity has exist",
  "e_37106": "Please ensure you have enough mystery box NFT. Kindly keep it in delist status when you open it.",
  "e_37100": "database error",
  "e_37001": "Mission has not finished",
  "e_37107": "activity only api user join",
  "e_37108": "activity module is not exist",
  "e_37101": "activity is not exist",
  "e_37110": "sorry, this activity is VIP only",
  "e_37104": "activity not started"
}