module.exports =  {
  "e_0": "Success",
  "e_10": "no repeatable request(usercenter)",
  "e_12307": "Please enable at least two security verifications.",
  "e_-1706": "Invalid username",
  "e_-1704": "Login passwords are the same",
  "e_-1702": "Wrong original login password",
  "e_-3504": "scyToken error",
  "e_-3503": "mfaToken error",
  "e_-3501": "gwToken error",
  "e_-1112": "Account already registered",
  "e_-1108": "Wrong invitation code",
  "e_-1106": "Invalid email address",
  "e_-1103": "Invalid phone number",
  "e_1006": "Account is disabled, please contact the main account",
  "e_1008": "User not exists",
  "e_1009": "The financial account is not allowed to log in to the web/app station.",
  "e_1010": "Your phone already bound",
  "e_1011": "This Phone already bound",
  "e_1012": "Your phone not bound",
  "e_1015": "Your mail not bound",
  "e_1016": "Google authenticator not bound",
  "e_1018": "Google authenticator reload",
  "e_1013": "Your mail already bound",
  "e_1014": "This Mail already bound",
  "e_1017": "Google authenticator already bound",
  "e_1023": "Not support account",
  "e_1029": "user has invited people",
  "e_1030": "Not support invite no",
  "e_1031": "invite code does exist",
  "e_1033": "invite code size limit exceed",
  "e_-1005": "Account is frozen due to security policies. Please contact customer service.",
  "e_-1002": "Invalid username or password, you have %d chances to retry",
  "e_1070": "client id not found",
  "e_-3008": "The account is abnormal, please try again later",
  "e_1091": "The main account is unavailable.",
  "e_-3004": "Account is frozen due to security policies, please try again after %d hours",
  "e_-3003": "Account is frozen due to security policies, please try again after %d hours",
  "e_-3002": "Account is frozen due to security policies, please try again after %d hours",
  "e_-3001": "Account is frozen due to security policies, please try again after %d hours",
  "e_1092": "Institutional KYC verification not passed.",
  "e_1093": "Sub-account creation limit reached.",
  "e_1094": "Your account has been cancelled",
  "e_1095": "Your account type does not support cancel",
  "e_1101": "Copy string literal text to the clipboard",
  "e_1500": "Header X-BM-CLIENT invalid",
  "e_1501": "Header X-BM-MERCHANT-CLIENT-ID is empty",
  "e_1502": "Header X-BM-MERCHANT-SIGN is empty",
  "e_1503": "Header X-BM-MERCHANT-TIMESTAMP is empty",
  "e_1505": "authorize code invalid",
  "e_1506": "You have submitted too many times, please try again tomorrow",
  "e_-2410": "kyc information does not exist",
  "e_1721": "underage",
  "e_1725": "invalid kyc status",
  "e_1726": "Not you sub account",
  "e_1727": "Sub account not allow login app",
  "e_1728": "No permission, please contact our administrator",
  "e_1732": "Invalid Information",
  "e_1733": "Invalid Country/Region",
  "e_1734": "Invalid Birthday",
  "e_1736": "Sorry, only letters(a-z), numbers(0-9), and periods(.), character(! # $ % * / ? ^ + - ` { | } ~ _) are allowed.",
  "e_1737": "Sorry, the character needs to be less than 32 characters.",
  "e_1738": "Sorry, please enter your valid email.",
  "e_1739": "You Haven't Certified Institutional KYC",
  "e_1740": "Your Application Is Pending Or Approved",
  "e_1741": "Your Apply Is Auditing Or Passed",
  "e_1742": "Your Apply Save Error",
  "e_1743": "Invite Relation Error",
  "e_1744": "Cashback Is Greater Than Agent Rebate",
  "e_1745": "Primary certification is required",
  "e_1750": "kyc level does not meet",
  "e_1751": "please check your name",
  "e_1752": "Please check your name (English)",
  "e_1753": "Submission is not supported in authentication.",
  "e_1754": "Special users cannot submit authentication.",
  "e_1755": "Internal users cannot apply for institutional certification.",
  "e_1756": "Sub account denied",
  "e_1757": "BitMart service is not available for the selected area.",
  "e_1758": "The BitMart.HK account and BitMart account are not interchangeable.",
  "e_1759": "Agent already exist",
  "e_1760": "System is abnormal, please try it later",
  "e_1763": "IP is not in the whitelist.",
  "e_1764": "Not mm-bot is forbidden to log in",
  "e_-46": "Account not found",
  "e_-40": "Request expired",
  "e_-36": "Forbidden",
  "e_-34": "Missing verification code",
  "e_-31": "Network busy, please refresh the page",
  "e_-30": "Visit too often, please try again later",
  "e_-23": "login code expired",
  "e_-18": "Wrong login password，you have %d chances to retry",
  "e_-14": "Invalid email verification code，you have %d chances to retry",
  "e_-13": "Invalid SMS verification code, you have %d chances to retry",
  "e_-12": "Invalid Google verification code，you have %d chances to retry",
  "e_-10": "Critical business exception",
  "e_-9": "Wrong email verification code",
  "e_-8": "Wrong SMS verification code",
  "e_-7": "Wrong captcha",
  "e_-6": "User not login",
  "e_-5": "Duplicate request",
  "e_-4": "Network error",
  "e_-3": "Invalid request",
  "e_-2": "Login too often, please try again after 2 hours",
  "e_-1": "Failure",
  "e_341036": "database err",
  "e_34100": "activity not find",
  "e_34101": "award not find",
  "e_34102": "user not join",
  "e_34103": "user has join",
  "e_34104": "over max ticket num",
  "e_34105": "balance not enough",
  "e_34107": "price coin not find",
  "e_34108": "cal snapshotBalance err",
  "e_34110": "your request is processing now, please wait",
  "e_34115": "no qualification",
  "e_34116": "Please open the contract",
  "e_34117": "Please try later.",
  "e_34135": "Your account has passed KYC-0, please complete KYC-1 first",
  "e_34136": "Your account has passed KYC-1, please complete KYC-2 first",
  "e_34138": "need QR code",
  "e_34140": "The function is not available in your country or area, please contact customer service if you have any questions.",
  "e_66000": "param error.",
  "e_66001": "The daily volume of is less than 10% of the available amount.",
  "e_66002": "IP is not in the whitelist",
  "e_66003": "user not authorized.",
  "e_66004": "api authorized error.",
  "e_66005": "mmbot user exists.",
  "e_66006": "user not exists.",
  "e_66007": "api key is not bound.",
  "e_66008": "api verify error.",
  "e_66009": "The quantity of each order should be between %s.",
  "e_33135": "Please complete your personal verification(Starter)",
  "e_33136": "Please complete your personal verification(Advanced)",
  "e_33137": "Services is not available in your countries and areas",
  "e_33138": "Your account has not yet completed the qr code certification, please complete first",
  "e_36003": "Query exception",
  "e_36009": "Order status is error",
  "e_36020": "This user does not exist",
  "e_36022": "This collectible does not exist",
  "e_36023": "This nft does not exist",
  "e_36026": "This order does not exist",
  "e_36032": "This status is not on sale",
  "e_36033": "lack inventory",
  "e_36034": "create order error",
  "e_36035": "request feign fail",
  "e_36036": "get userInfo error",
  "e_36037": "not purchasable timing",
  "e_36038": "NFT has sold",
  "e_36041": "not has NFT",
  "e_36042": "account is not enough",
  "e_36043": "have no coin info",
  "e_36045": "Risk operation,please try it again.",
  "e_36046": "account refund fail",
  "e_36044": "system config not init or unknown network",
  "e_36047": "nft withdraw fail",
  "e_36049": "withdraw fee changed",
  "e_36050": "exist nft is not this user",
  "e_36053": "The wallet is frozen,please check it.",
  "e_36054": "get dollar rate error",
  "e_36061": "query nft does not exist",
  "e_36065": "Risk operation,please try it in safe environment .",
  "e_36069": "Incorrect purchase, you are the owner of this item",
  "e_36080": "Sorry, the NFT item can’t be purchased.",
  "e_36081": "Sorry, the NFT item can’t be listed.",
  "e_36082": "Sorry, you can’t deposit the NFT item.",
  "e_36083": "Sorry, This NFT collection does not support withdrawal.",
  "e_36090": "Account has been frozen , please contact with us.",
  "e_36091": "Withdraw prohibited, please contact with us.",
  "e_36092": "Deposit prohibited, please contact with us.",
  "e_36093": "Trading prohibited, please contact with us.",
  "e_36094": "Listing prohibited, please contact with us.",
  "e_36095": "Listing nft fail",
  "e_36096": "subtract nft quality fail",
  "e_36097": "NFT quality is not enough",
  "e_36098": "DeListing nft fail",
  "e_36100": "This nft item does not exist",
  "e_36101": "purchase nft database error",
  "e_36102": "item data error",
  "e_36118": "nft not set price",
  "e_36121": "This collectible is not online",
  "e_36124": "You have reached the purchase limit for the collection.",
  "e_36127": "Please try later, frequent commit.",
  "e_36133": "has NFT is trading",
  "e_36134": "nft list price must not be greater than %s usd.",
  "e_36137": "The operation is frequent. Please try again later.",
  "e_47000": "Contract future activity submit error",
  "e_47001": "Invalid team join code",
  "e_47002": "Concurrent join team failed",
  "e_47003": "Not in sign up time",
  "e_47004": "User is team leader",
  "e_47005": "User has joined team",
  "e_47006": "User contract balance not enough",
  "e_47007": "User risk check failed",
  "e_47008": "Team name exist",
  "e_47009": "Team code exist",
  "e_-60": "Partial success",
  "e_0,": "Success",
  "e_-35": "Service unavailable",
  "e_-2001": "Select record error",
  "e_-2000": "No record",
  "e_-3202": "Invalid type",
  "e_-3201": "Invalid coinType",
  "e_-37": "Force update",
  "e_-33": "Invalid signature",
  "e_39000": "PARAM_NOT_EMPTY",
  "e_39100": "SYSTEM_ERROR",
  "e_39101": "BIZ_SOURCE_NOT_EXIST",
  "e_39102": "BIZ_TYPE_NOT_EXIST",
  "e_39103": "USER_BENEFIT_EXIST_DUPLICATE",
  "e_39104": "USER_BENEFIT_GRANTING",
  "e_39105": "BENEFIT_VALUE_TYPE_NOT_EXIST",
  "e_39107": "USER_BENEFIT_STATUS_NOT_EXIST",
  "e_39108": "USER_BENEFIT_STATUS_ERROR",
  "e_39109": "USER_BENEFIT_VERIFY_NUM_NOT_ENOUGH",
  "e_39110": "USER_BENEFIT_SOURCE_NUM_NOT_ENOUGH",
  "e_39111": "USER_BENEFIT_VERIFY_ORDER_STATUS_ERROR",
  "e_39112": "USER_BENEFIT_NOT_EXIST",
  "e_39113": "USER_BENEFIT_FREEZING",
  "e_39114": "USER_BENEFIT_PROVING",
  "e_39117": "USER_BENEFIT_GRANT_FAIL",
  "e_39118": "USER_BENEFIT_RECYCLE_NUM_NOT_ENOUGH",
  "e_39119": "USER_BENEFIT_NFT_BLIND_BOX_NOT_SUPPORT",
  "e_39120": "USER_BENEFIT_SPOT_COIN_PROCESSING",
  "e_39121": "PARAM_VALUE_NOT_EXIST",
  "e_39122": "USER_BENEFIT_VERIFY_ORDER_EXIST",
  "e_39129": "AMOUNT_MUST_MORE_THAN_ZERO",
  "e_39130": "BENEFIT_GRANT_CID_REPEAT",
  "e_39131": "BENEFIT_FREEZE_CALCULATE_ERROR",
  "e_39132": "BENEFIT_EXPORT_ERROR",
  "e_39123": "BENEFIT_NOT_EXIST",
  "e_39124": "BENEFIT_GRANT_MORE_THAN_NUMBER",
  "e_39125": "BENEFIT_NAME_DUPLICATE",
  "e_39126": "BENEFIT_GRANT_CID_NOT_EXIST",
  "e_39127": "PARAM_LENGTH_ERROR",
  "e_39128": "PARAM_NOT_EXIST",
  "e_39133": "USER_BENEFIT_GRANT_ORDER_EXIST",
  "e_39115": "USER_BENEFIT_RECYCLING",
  "e_39116": "USER_BENEFIT_REFUNDING",
  "e_33001": "Your account is frozen due to security policies. Please contact customer service",
  "e_33002": "Method Not Allowed",
  "e_33000": "Bad Request",
  "e_33003": "Unsupported Media Type",
  "e_33004": "Internal Server Error",
  "e_33100": "User account not found",
  "e_33101": "Symbol not found",
  "e_33102": "Balance not enough",
  "e_33103": "User stop trading",
  "e_33104": "This Symbol is stop trading",
  "e_33105": "REQUEST_PARAM_MISS",
  "e_33106": "REQUEST_PARAM_NOT_MATCH",
  "e_33107": "Order is already canceled",
  "e_33108": "Order is already completed",
  "e_33109": "Order does not exist",
  "e_33110": "Orders is canceled partially",
  "e_33111": "Symbol not used",
  "e_33114": "Service unavailable",
  "e_33112": "The buy order price cannot be higher than the open price",
  "e_33115": "kyc invalid level, you need to verify kyc level2",
  "e_33118": "The price is low and there is no matching depth",
  "e_33119": "cancel failed, order is not revocable status",
  "e_33116": "kyc invalid country, services are not available",
  "e_33117": "The price is high and there is no matching depth",
  "e_33113": "The sell order price cannot be lower than the open price",
  "e_33120": "No permission, please contact the main account",
  "e_33121": "Account restricted",
  "e_33122": "This trading pair is not available to trade in your region",
  "e_33123": "Network timeout, please try again",
  "e_33124": "SIZE_NOT_MATCH",
  "e_33125": "PRICE_NOT_MATCH",
  "e_33126": "SIZE_MUL_PRICE_NOT_MATCH",
  "e_33127": "NOTIONAL_NOT_MATCH",
  "e_33128": "NOTIONAL_IS_SMALL",
  "e_33129": "SIZE_IS_SMALL",
  "e_33130": "orderModeCode not match",
  "e_33131": "subOrderModeCode not match",
  "e_33132": "Operation is limited, please try again later",
  "e_33133": "The number of orders exceeds the maximum limit",
  "e_33134": "No permission for this pair",
  "e_33139": "Insufficient balance or frozen amount",
  "e_33140": "Quantity is too small",
  "e_33141": "Trading order failure",
  "e_33142": "Loan success,but trading order failure",
  "e_33143": "Insufficient loan amount",
  "e_33144": "This pair is abnormal or will be delist，suspend trading/borrowing/transfer",
  "e_33145": "Borrowing of this currency has been suspended",
  "e_33146": "This account is restricted from borrowing",
  "e_33147": "This sub-account does not belong to the current main account",
  "e_34019": "The system has received your request and will inform you later by SMS or email",
  "e_34044": "coin's name not match",
  "e_34048": "Org recharge balanced check",
  "e_34040": "Org recharge failed",
  "e_34037": "This order status cannot be withdrawn",
  "e_34021": "the subscribe amount should be greater than order min amount",
  "e_34061": "can not advance redeem",
  "e_34051": "The address of the currency is not configured",
  "e_34042": "The network is unstable, please try again later",
  "e_34041": "Org withdraw failed",
  "e_34018": "need update app",
  "e_34027": "LoginNameList account does not exist",
  "e_34050": "Org withdraw abnormal order timeout 60 second",
  "e_34014": "Institutional users are not allowed to subscribe",
  "e_34047": "Org recharge amount check",
  "e_34049": "Auto subscribe product not exist",
  "e_34045": "机构充提中超过4小时",
  "e_34000": "System exception",
  "e_34052": "This currency does not support withdrawal",
  "e_34060": "Order has advance redeem",
  "e_34022": "the subscribe amount should be less than order max amount",
  "e_34026": "LoginNameList length should be less than 100",
  "e_34039": "Org withdraw address is blank",
  "e_34046": "Org recharge or withdrawal result error more than 4 hours",
  "e_34043": "Order does not exist",
  "e_34036": "The order status cannot be recharged",
  "e_53029": "Receive Failed. Please contact customer service.",
  "e_53000": "System exception",
  "e_53027": "risk check not pass",
  "e_53012": "the gift is for the specific user",
  "e_53024": "create param error",
  "e_53005": "exceed total daily amount",
  "e_53008": "the password is invalid",
  "e_53003": "exceed min amount",
  "e_53025": "specify user is empty",
  "e_53016": "no passphrase",
  "e_53009": "gift is all received",
  "e_53019": "red packet duplicate receive",
  "e_53010": "the gift is only for the sender's referral",
  "e_53020": "red packet receive failed",
  "e_53001": "Insufficient balance",
  "e_53026": "specify user is not empty",
  "e_53014": "you can only receive one new user crypto gift",
  "e_53028": "the operation is too frequent, please try again later.",
  "e_53011": "the gift is expired",
  "e_53023": "receive cid not exist",
  "e_53018": "red packet to redis failed",
  "e_53006": "no such red packet type",
  "e_53013": "the gift is for the new register user",
  "e_53015": "passphrase generate failed",
  "e_53022": "coin current not found",
  "e_53017": "no such red packet",
  "e_53030": "Create not allowed",
  "e_53021": "no such user type",
  "e_53007": "user not found",
  "e_53004": "exceed max amount",
  "e_s": "Mission not end",
  "e_37109": "sorry , this activity you can't join",
  "e_37103": "user has into activity",
  "e_37105": "activity is over",
  "e_37002": "Mission not start",
  "e_37102": "activity has exist",
  "e_37106": "Please ensure you have enough mystery box NFT. Kindly keep it in delist status when you open it.",
  "e_37100": "database error",
  "e_37001": "Mission has not finished",
  "e_37107": "activity only api user join",
  "e_37108": "activity module is not exist",
  "e_37101": "activity is not exist",
  "e_37110": "sorry, this activity is VIP only",
  "e_37104": "activity not started",
  "e_-2200": "User needs to bind Google authenticator or phone to change address.",
  "e_-2203": "Coin does not exist",
  "e_-2204": "Request too long",
  "e_-2205": "Memo is empty",
  "e_-2206": "Invalid address",
  "e_-2215": "Please check your memo",
  "e_-2207": "Address already exists",
  "e_-2208": "Address can not be updated",
  "e_-2209": "Address does not exist",
  "e_-2210": "This currency withdrawal is suspended",
  "e_-2103": "Minimum withdraw count %s",
  "e_-2105": "Balance not enough",
  "e_-2106": "Unsupported operation",
  "e_-2107": "Exceed daily withdrawal quota, for your safety, please wait 24 hours and try again",
  "e_-2109": "please check The Email /Phone number/BitMart ID And try again",
  "e_-2110": "can not get user info, please try again",
  "e_-2111": "Monitor that the withdrawal will cause the overall spot wallet to fall below the Margin call risk rate. Please revise the withdrawal amount as appropriate.",
  "e_-2112": "Sub-account does not support withdraw",
  "e_-2113": "Missing authentication name",
  "e_-2114": "Sub-account does not support deposit",
  "e_-2115": "Please complete your institution verification to enable withdrawal function.",
  "e_-2116": "Deposit amount should be within {0.000001}-{0.1}",
  "e_-2117": "Saving BTC-lightning invoice is not supported.",
  "e_-2118": "Failed to get invoice fee",
  "e_-2119": "The input amount does not match the parsed amount",
  "e_-2121": "Invoice is invalid",
  "e_-2122": "Invoice has expired, please re-create",
  "e_-2123": "This network not support domain address",
  "e_-2124": "Domain is invalid",
  "e_-2125": "Given you have deposited crypto through P2P trading within 24 hours, the equivalent value of the deposit( %s USDT) can not be withdrawaled in %s hours.",
  "e_-2126": "Withdrawal amount must be an integer multiple of %s",
  "e_-2150": "Your account does not support Convert",
  "e_-2151": "You have converted once today, please come back tomorrow",
  "e_-2152": "The currency price fluctuates too much, please try again later.",
  "e_-2153": "The amount of a single conversion shall not exceed 20U",
  "e_-2154": "System error, please try again later",
  "e_-2155": "Your account status is abnormal and cannot be converted",
  "e_-2156": "Advanced Identity Verification needs to be completed first",
  "e_-2157": "Insufficient balance",
  "e_-2211": "Query withdraw fee error",
  "e_-2212": "Create withdraw fee token error",
  "e_-2250": "Credit Account not found",
  "e_-2251": "The current user has no credit pledge assets",
  "e_-2252": "There is no credit pledge asset in the current currency",
  "e_-2253": "Insufficient account balance",
  "e_-2300": "No matching coin",
  "e_-2301": "Withdraw forbidden",
  "e_-2302": " internal Withdraw forbidden",
  "e_3014": "The withdrawal user and the target user cannot be the same",
  "e_-5100": "Account unavailable, disabled in background",
  "e_-5101": "No matching coin",
  "e_-5102": "Asset transfer between accounts is not available,permission closed by main account or background",
  "e_-5103": "Can't transfer to oneself",
  "e_-5104": "Sub account does not have permission",
  "e_-5105": "Can't find source account",
  "e_-5106": "Can't find target account",
  "e_-5107": "Unsupported transfer type",
  "e_-5108": "Only support sub-account",
  "e_-5109": "Unsupported transfer type",
  "e_-5111": "Account unavailable, Frozen by main account",
  "e_-5112": "The sub-account function only supports organization accounts",
  "e_-5113": "Suspend transfer out",
  "e_-35600": "This coin is suspend transfer.",
  "e_-35601": "This account is restricted from Margin transfer.",
  "e_-35602": "Margin account not opened.",
  "e_-35603": "This pair will be delisted from Isolated Margin. Suspend transfer.",
  "e_12501": "currency does not exist",
  "e_12518": "The transfer function is under maintenance, please try again later.",
  "e_12520": "Your account has not yet completed the kyc advanced certification, please complete first",
  "e_32000": "Request parameter exception",
  "e_32001": "Parameter verification failed",
  "e_32002": "Our Buy & Sell module is temporarily unavailable due to system maintenance. We apologize for any inconvenience this may cause.",
  "e_32003": "Buy & Sell is under maintenance.",
  "e_32004": "Does not support current digital currency.",
  "e_32005": "Does not support current fiat currency.",
  "e_32010": "The current currency does not support recharge",
  "e_32011": "Unable to get the digital currency recharge address",
  "e_32012": "Order creation failed",
  "e_32013": "Order payment status update failed",
  "e_32014": "Transaction failed. Please consider increasing the purchase amount or using a different service provider",
  "e_32015": "Failed to initiate a currency sale transaction",
  "e_32016": "User registration time does not exist",
  "e_32017": "Does not support the current payment channel",
  "e_32018": "Failed to create MoonPay payment link",
  "e_32019": "Failed to query MoonPay purchase order",
  "e_32020": "This user does not exist",
  "e_32023": "Failed to query the limit on the number of digital currencies sold",
  "e_32024": "Failed to create MoonPay sell currency link",
  "e_32025": "Failed to send encrypted currency, the current operation is not supported.",
  "e_32026": "Failed to query the total number of digital currency orders.",
  "e_32027": "Failed to query the detail of digital currency orders.",
  "e_32028": "Failed to query currency information.",
  "e_32029": "Failed to access service provider, please refresh the page.",
  "e_32030": "Failed to query user info.",
  "e_32031": "Failed to query sdk param.",
  "e_32032": "interface version does not support.",
  "e_32050": "Query network fee failed.",
  "e_32052": "Query withdraw day quota failed.",
  "e_32053": "Query coin rate failed.",
  "e_32054": "The user's cash withdrawal exceeds the daily limit.",
  "e_32055": "The user's cash withdrawal amount is less than the withdrawal fee.",
  "e_32056": "The user's cash withdrawal amount is less than minimum withdrawal amount.",
  "e_32084": "Please complete your institution verification to enable withdrawal function.",
  "e_32100": "Failed to query the list of legal currencies supported by moonpay",
  "e_32101": "Failed to query the list of digital currencies supported by moonpay",
  "e_32102": "Failed to query moonpay to purchase digital currency quotation",
  "e_32103": "Failed to query moonpay's digital currency quotation",
  "e_32104": "The buy transaction of MoonPay is cancelled",
  "e_32106": "Failed to update order information based on moonpay feedback",
  "e_32107": "Failed to query the quotation of digital currency purchase by simplex",
  "e_32108": "Failed to query the quotation of digital currency sold by simplex",
  "e_32109": "Failed to send digital currency purchase request to simplex",
  "e_32110": "Failed to send request to sell digital currency to simplex",
  "e_32211": "Parameter signature error",
  "e_32212": "Access token get fail",
  "e_32200": "Failed to obtain the balance of the specified currency in the user's specified account",
  "e_32201": "Failed to freeze user account assets",
  "e_32112": "The current virtual currency deposit is closed",
  "e_32113": "The current virtual currency does not exist",
  "e_32114": "Virtual currency configuration information is abnormal and cannot be traded",
  "e_32115": "The user account balance is insufficient and the operation failed.",
  "e_32116": "Withdrawal request parameter verification failed",
  "e_32117": "The order has been withdrawn, and the corresponding serial id cannot be found",
  "e_32118": "The withdrawal amount is less than the minimum withdrawal amount",
  "e_32119": "User's fiat currency account wallet freeze failed",
  "e_32120": "Network error, failed to send withdrawal request",
  "e_32121": "Failed to verify the parameters of the request to obtain the transaction id on the chain",
  "e_32122": "Network error, failed to query transaction information after the virtual currency was on the chain",
  "e_32123": "Failed to update the withdrawal address in the token sale order",
  "e_32124": "Failed to update the withdrawal id in the legal currency withdrawal order",
  "e_32125": "Failed to update the local processing status in the legal currency withdrawal order",
  "e_32126": "Failed to update the withdrawal quantity in the legal currency withdrawal order",
  "e_32202": "Unfreeze and return user account assets failed",
  "e_32203": "Deduction of user account assets failed",
  "e_32900": "Network error",
  "e_32901": "Network error, http call error",
  "e_32902": "Network error, Grpc call error",
  "e_32800": "Fiat biz switch update failed",
  "e_32801": "Channel coin is empty",
  "e_32802": "Channel currency is associated",
  "e_44004": "DB_ERROR",
  "e_42000": "SYSTEM_ERROR",
  "e_42001": "REQUEST_TOO_FREQUENTLY",
  "e_42003": "USER_NOT_LOGIN",
  "e_42002": "PARAM_NOT_EMPTY",
  "e_42005": "UN_KNOW_DESCRIPTION",
  "e_42006": "LOCALE_CONFIG_NOT_EXIST",
  "e_42007": "UP_LOCALE_NOT_SUPPORT_UPDATE_NAME",
}