module.exports =  {
  "e_0": "Successful",
  "e_1": "Operation is too Frequent. Please try again later",
  "e_2": "Operation is too Frequent. Please try again later",
  "e_3": "The requested parameter is invalid. Please try again later",
  "e_4": "The server is busy now. Please try again later",
  "e_5": "System is abnormal, pls try it later",
  "e_6": "Please login first",
  "e_7": "Captcha validation doesn't match. Please try again",
  "e_8": "SMS verification code doesn't match. Please try again",
  "e_9": "Email verification code doesn't match. Please try again",
  "e_12": "Google Authenticator code doesn't match. You have {0} chance(s) to try",
  "e_13": "Sms verification code doesn't match. You have {0} chance(s) to try",
  "e_14": "Email verification code doesn't match. You have {0} chance(s) to try",
  "e_18": "Invalid username or password. You have {0} chance(s) to try",
  "e_19": "Username doesn't exist. Please try again",
  "e_20": "The password is incorrect. Please re-enter your password",
  "e_21": "Please set your withdrawal password first",
  "e_22": "Withdrawal password doesn't match. You have {0} chance(s) to try",
  "e_30": "Operation is too Frequent. Please try again later",
  "e_31": "The verification code has expired, please resend",
  "e_32": "The server is busy now. Please try again later",
  "e_33": "The server is busy now. Please try again later",
  "e_34": "The server is busy now. Please try again later",
  "e_35": "Service is unavailable now",
  "e_36": "The server is busy now. Please try again later",
  "e_38": "Please select the withdrawal address",
  "e_40": "Please set your system time to correct time.",
  "e_41": "The server is busy now. Please try again later",
  "e_42": "The server is busy now. Please try again later",
  "e_43": "The server is busy now. Please try again later",
  "e_44": "The server is busy now. Please try again later",
  "e_45": "The server is busy now. Please try again later",
  "e_403": "Please try again later or contact customer service",
  "e_429": " Please try again later",
  "e_500": "The server is busy now. Please try again later",
  "e_175": "User Has Certified Institutional KYC",
  "e_1000": "Username doesn't exist. Please try again",
  "e_1001": "Username and password don't match. Please try again",
  "e_1002": "Username and password don't match. You still have {0} chance(s) to try",
  "e_1003": "Username doesn't exist. Please try again",
  "e_1004": "The server is busy now. Please try again later[1004]",
  "e_1005": "Your account may be at risk. Please contact our BitMart customer service",
  "e_1029": "This account has been risk controlled",
  "e_1030": "The format of the referral code is incorrect (it can only contain 6-13 letters and numbers, no special characters).",
  "e_1031": "The referral code is already occupied.",
  "e_1032": "Rebate ratio setting does not exceed the limit.",
  "e_1033": "Referral code amount has excceeded the upper limit.",
  "e_1091": "Main account is not available",
  "e_1092": "Lack of institutional KYC verification",
  "e_1093": "Maximum number of sub-accounts",
  "e_1100": "The server is busy now. Please try again later",
  "e_1101": "Passwords must have at least 8 characters and contain four of the following: uppercase letters, lowercase letters, numbers, and symbols.",
  "e_1102": "This account has been registered. Please enter another one",
  "e_1103": "Please enter a valid phone number",
  "e_1105": "This email address already exists. Please enter a new one",
  "e_1106": "Please enter a valid email address",
  "e_1108": "Please enter a valid invitation code",
  "e_1109": "This invitation code has already existed",
  "e_1110": "This phone number is already bound to another account",
  "e_1111": "This email is already bound to another account",
  "e_1112": "This account has been registered. Please enter another one",
  "e_1203": "Please enter a valid phone number",
  "e_1204": "Please enter a valid phone number",
  "e_1205": "Please enter a valid phone number",
  "e_1206": "This phone number has been bound to another account and can't be used for registration",
  "e_1207": "Please bind your account with phone number first",
  "e_1304": "Please enter an email address",
  "e_1305": "Please enter a valid email address",
  "e_1306": "This email address has been bound to another account",
  "e_3000": "The server is busy now. Please try again later",
  "e_1401": "Please enable your 2FA via Google Authenticator",
  "e_1500": "Please enter a valid phone number",
  "e_1501": "Your account has already been bound your phone number",
  "e_1502": "Please bind your account to your phone number first",
  "e_1505": "SMS verification code doesn't match. Please try again",
  "e_1507": "This phone number has been bound to another account",
  "e_1550": "Please enter a valid email address",
  "e_1551": "Email has been bound",
  "e_1552": "Email hasn't been bound",
  "e_1555": "Email verification code doesn't match. Please try again",
  "e_1557": "This email address has been bound to another account",
  "e_1600": "Please enter a valid ID number",
  "e_1601": "Please enter a valid ID number",
  "e_1602": "Please enter a valid ID number",
  "e_1603": "Please enter a valid name",
  "e_1604": "This ID number has been used on another account",
  "e_1606": "Please enter a valid name",
  "e_1700": "Two passwords are inconsistent",
  "e_1701": "Please enable 2FA via your phone number, email or Google Authenticator",
  "e_1702": "Login password doesn't match",
  "e_1703": "Withdrawal password doesn't match",
  "e_1704": "Your new password can't be the same with your old one",
  "e_1705": "Your new password can't be the same with your old one",
  "e_1706": "The username doesn't exist",
  "e_1721": "Age must be greater than 18.",
  "e_1722": "Age must be less than 75.",
  "e_1731": "User Has Certified Personal KYC",
  "e_1732": "Invalid Information",
  "e_1733": "Invalid Country/Region",
  "e_1734": "Invalid Birthday",
  "e_1739": "You Haven't Certified Institutional KYC",
  "e_1740": "Your Application Is Pending Or Approved",
  "e_1751": "Please check your name",
  "e_1752": "Please check your name（English）",
  "e_1753": "Submission is not supported in authentication.",
  "e_1754": "Special users cannot submit authentication.",
  "e_1755": "Internal users cannot apply for institutional certification.",
  "e_1800": "This coin can't be traded now",
  "e_1802": "Amount must be greater than {0} {1}",
  "e_1803": "Maximum exchanging amount {0}",
  "e_1804": "Minimum limit order price {0}",
  "e_1805": "Minimum limit order total {0}",
  "e_1806": "Limit order price can't be higher than limit up price {0}",
  "e_1807": "Limit order price can't be lower than limit down price {0}",
  "e_1823": "The buy order price cannot be higher than the open price",
  "e_1824": "The sell order price cannot be lower than the open price",
  "e_1808": "Total must be greater than {0} {1}",
  "e_1809": "Amount must be greater than {0}",
  "e_1810": "The trading is closed now",
  "e_1811": "{0} balance is insufficient",
  "e_1812": "You can sell at most {0}",
  "e_1815": "Everyday's maximum effective limit order times {0}",
  "e_1816": "This coin can not be traded",
  "e_1817": "Sorry, your account doesn't have the operating authorization",
  "e_1818": "Maximum limit order price {0}",
  "e_1819": "Your order amount exceeds the maximum purchase amount",
  "e_1820": "Order prohibited",
  "e_1900": "No coin matches",
  "e_1901": "Restricted legal currency",
  "e_1902": "This coin has no competition",
  "e_2000": "No record",
  "e_2107": "You have exceeded the daily withdrawal limit. For your safety, please wait 24 hours and try again",
  "e_2108": "For safety concerns, please complete the identity Verification Process first",
  "e_2101": "Please enable 2FA via your phone number, email, or Google Authenticator",
  "e_2102": "Your daily available withdrawal times:{0}",
  "e_2103": "Minimum withdrawal amount:{0}",
  "e_2104": "Maximum withdrawal amount:{0}",
  "e_2105": "Insufficient balance",
  "e_2106": "Users can't exchange with each other within BitMart",
  "_e_2200": "Please enable two-factor authentication via",
  "e_2203": "No coin matches",
  "e_2204": "The remark is too long",
  "e_2205": "Please enter your address memo",
  "e_2206": "The address format is wrong. Please check the address length/character and try again.",
  "e_2207": "This address has already existed",
  "e_2208": "This address is your deposit address",
  "e_2209": "Your address is not available",
  "e_2215": "Please check your memo",
  "e_2211": "Withdrawal to contract address is not supported",
  "e_2300": "No coin matches",
  "e_2301": "Withdraw forbidden",
  "e_2400": "This file format is not supported",
  "e_2401": "The server is busy now. Please try again later",
  "e_2402": "Verified sucessfully",
  "e_2403": "The server is busy now. Please try again later",
  "e_2404": "The server is busy now. Please try again later",
  "e_2405": "Please enter a valid ID number",
  "e_2406": "This ID number has been used on another account",
  "e_2410": "Your account is already in verification and no other new verification is available.",
  "e_2501": "Invalid link",
  "e_2502": "The link is expired",
  "e_2691": "You haven't bound Google Authenticator ",
  "e_2701": "You have already voted 11 times today",
  "e_2703": "You don't have enough BMX to vote",
  "e_2704": "You can only vote at most 11 times a day",
  "e_2705": "You have already shared today",
  "e_2801": "The investment of this project is closed now",
  "e_2802": "The project doesn't exist",
  "e_2803": "You can't invest in this project now",
  "e_2804": "Please reduce your amount and try again",
  "e_2805": "Insufficient balance",
  "e_2806": "Your amount must be a multiple of 100",
  "e_2807": "No records",
  "e_2808": "You can't renew the investment now",
  "e_2690": "You have enabled 2FA via Google Authenticator",
  "e_2170": "You have exceeded the daily withdrawal limit. For your safety, please wait 24 hours and try again",
  "e_3001": "Too many failed attempts. Please try an hour again later",
  "e_3002": "Too many failed attempts. Please try an hour again later",
  "e_3003": "Too many failed attempts. Please try an hour again later",
  "e_3004": "Too many failed attempts. Please try an hour again later",
  "e_3005": "Please contact BitMart customer service to reset your password",
  "e_3006": "Too many failed attempts. Please try an hour again later",
  "e_3007": "Your account has been temporarily frozen for security concerns. Please try again later",
  "e_3101": "You have a API with duplicate memo",
  "e_3103": "The size of the trusted IP list should be less than or equal to 10",
  "e_3104": "User can create at most 5 APIs",
  "e_3301": "You are not entitled to enable this service",
  "e_3501": "Validation failed, please refresh and try again",
  "e_3502": "The server is busy now. Please try again later",
  "e_9999": "The server is busy now. Please try again later",
  "e_10010": "You have voted this coin today!",
  "e_10011": "You have already voted three coins today!",
  "e_12201": "Less than the limit amount",
  "e_12203": "The document information is inconsistent with the intermediate verification information. Please re-upload or contact customer service.",
  "e_12519": "Transfer Failed. Please close the cross positions in the futures account and try again.",
  "e_14102": "Current currency not available",
  "e_14103": "Current currency not available",
  "e_14111": "Current currency not supported by current channel",
  "e_14112": "Channel not exist",
  "e_14113": "Channel not available",
  "e_14114": "The financial institution is not supported by the current channel",
  "e_14115": "The bank is unavailable temporary",
  "e_14201": "Fiat identification unverified",
  "e_14230": "User unauthorized to deposit in the current channel",
  "e_14231": "User unauthorized to withdraw in the current channel",
  "e_14302": "Selected bank card not exist",
  "e_14303": "Selected bank card not bound. Please delete and rebind",
  "e_14304": "The channel associated with the selected card is not available",
  "e_14305": "Do not repeat the binding",
  "e_14306": "The number of bound accounts exceeds the limit",
  "e_14310": "Failed to delete the bank card",
  "e_14311": "This account can’t be deleted because a transaction is pending. Please wait for the transaction to complete and then delete the account.",
  "e_14320": "Deposit function of selected bank card frozen",
  "e_14321": "Withdrawal function of selected bank card frozen",
  "e_14322": "Deposit function of selected bank card not enabled",
  "e_14323": "Withdrawal function of selected bank card not enabled",
  "e_14324": "Selected bank card not verified",
  "e_14350": "Session expired. Please re-enter username and password",
  "e_14351": "MFA is required to link the bank card",
  "e_14352": "Bank card username or password is incorrect",
  "e_14353": "Bank login attempt too many times.",
  "e_14362": "Binding failed, the number of accounts has exceeded the limit",
  "e_14363": "Routing num is incorrect",
  "e_14371": "Routing num is incorrect",
  "e_14372": "Account num is incorrect",
  "e_14401": "Platform account not exist",
  "e_14500": "Current service unavailable",
  "e_14501": "Deposit/withdrawal amount cannot be empty",
  "e_14502": "Deposit/withdrawal amount should be greater than 0",
  "e_14503": "Transfer amount less than handling fee",
  "e_14550": "Failed to generate Order ID",
  "e_14521": "Account is temporarily frozen",
  "e_14522": "Daily total amount limit",
  "e_14523": "Daily frequency limit",
  "e_14524": "Large transaction, under review",
  "e_14531": "Failed to cancel",
  "e_14551": "Failed to generate wire deposit Order Reference No.",
  "e_14601": "Failed to freeze the wallet balance, unable to withdraw",
  "e_14602": "Insufficient balance available for wallet withdrawal",
  "e_17000": "Session is closed",
  "e_17001": "The quota has been snapped up",
  "e_17002": "Activity not started",
  "e_17003": "Activity not started",
  "e_17004": "The activity is over",
  "e_17005": "The activity is over",
  "e_17006": "Activity does not exist",
  "e_17007": "Less than the minimum purchase quantity",
  "e_17008": "Greater than maximum purchase quantity",
  "e_17009": "The system is busy, please try again later",
  "e_17010": "Do not repurchase",
  "e_17011": "The activity is over",
  "e_17012": "The system is busy, please try again later",
  "e_17013": "The activity is over",
  "e_17999": "he system is busy, please try again later",
  "e_20000": "Activity has not started",
  "e_20001": "Operation is too Frequent. Please try again later",
  "e_20002": "Operation is too Frequent. Please try again later",
  "e_20004": "Insufficient balance",
  "e_20005": "Minimum lock amount",
  "e_20006": "Exceeded the maximum lock amount",
  "e_20007": "Operation is too Frequent. Please try again later",
  "e_20008": "This event hasended",
  "e_20009": "You are noteligible toparticipate",
  "e_18001": "The file format does not match the requirements",
  "e_18002": "The file format does not match the requirements",
  "e_18003": "The file is abnormal. Please upload it again",
  "e_18004": "The file has exceeded the limit",
  "e_18005": "The file cannot be empty",
  "e_18006": "The file is abnormal. Please upload it again",
  "e_16003": "No deduction is supported",
  "e_190001": "No currency exists",
  "e_190002": "This currency is not trading",
  "e_191001": "Currency prices are not available",
  "e_193001": "Verfication unsuccessful",
  "e_193002": "Failed to obtain authentication information",
  "e_194001": "The currency cannot be empty",
  "e_194002": "The price cannot be empty",
  "e_194003": "The amount cannot be empty",
  "e_194004": "/",
  "e_194005": "The uid cannot be empty",
  "e_194006": "Beyond maximum accuracy",
  "e_194007": "Exceed maximum limit",
  "e_194008": "Less than minimum limit",
  "e_194101": "Order does not exist",
  "e_194102": "Trading confirmed",
  "e_194103": "The exchange rate has changed. Please place a new order",
  "e_194104": "Trading failure",
  "e_194105": "Platform account balance is insufficient, temporarily can not carry out trading",
  "e_194106": "Insufficient balance. Please enter again",
  "e_194107": "Trading in progress",
  "e_194108": "The exchange rate has changed. Please place a new order",
  "e_194109": "Please select a payment method",
  "e_194110": "Payment does not exist",
  "e_194111": "Current payment method is not supported",
  "e_194009": "Service temporarily unavailable.",
  "e_194010": "Amount exceeds limit.",
  "e_27000": "The event has completed",
  "e_33000": "System is abnormal. Please try it later",
  "e_33002": "System is abnormal. Please try it later",
  "e_33003": "System is abnormal. Please try it later",
  "e_33004": "System is abnormal. Please try it later",
  "e_33100": "System is abnormal. Please try it later",
  "e_33101": "System is abnormal. Please try it later",
  "e_33102": "Balance not enough",
  "e_33103": "Account has been frozen",
  "e_33104": "Trading suspended",
  "e_33105": "Order shortage parameter",
  "e_33106": "The order does not comply with the rules",
  "e_33107": "Order has been canceled",
  "e_33108": "Order has been filled",
  "e_33109": "Order is not exist",
  "e_33110": "Partial cancellation of order failed",
  "e_33111": "Trading suspended",
  "e_33112": "The buy order price cannot be higher than the open price",
  "e_33113": "The sell order price cannot be lower than the open price",
  "e_33114": "Trading not started",
  "e_33117": "The quote price is too high to find matched depth",
  "e_33118": "The quote price is too low to find matched depth",
  "e_33119": "cancel failed, ioc order is not allowed to cancel",
  "e_1010": "This phone number already exists.",
  "e_1011": "This phone number already exists.",
  "e_1012": "This phone unbound.",
  "e_1013": "This email already exists.",
  "e_1014": "This email already exists.",
  "e_1015": "This email unbound.",
  "e_1016": "This Google Authenticator unbound.",
  "e_1017": "Google Authenticatoris bound.",
  "e_1018": "Please reload the Google Authenticator.",
  "e_1070": "User id not found",
  "e_21201": "Activity does not exist",
  "e_21205": "Activity has not started",
  "e_21206": "The event is completed",
  "e_21252": "Insufficient balance",
  "e_12502": "The currency is under maintenance, deposit is suspended.",
  "e_12506": "The currency is under maintenance, withdrawal is suspended.",
  "e_12505": "Amount limit 50-20000 USD.",
  "e_12504": "Withdrawal timed out. Please re-initiate withdrawal",
  "e_12508": "Transfer is abnormal. Please try it later",
  "e_12509": "Pls active Future service first",
  "e_12510": "Insufficient balance",
  "e_12511": "Pls active Future service first",
  "e_12512": "Pls active Future service first",
  "e_12513": "Less than the minumun transfer limit",
  "e_21253": "Lock failed",
  "e_21254": "Lock failed",
  "e_21255": "The maximum number of lock-able positions is {0}BMX",
  "e_21256": "Less than the minimum lock amount",
  "e_21257": "Greater than the maximum number of locks",
  "e_1020": "You cannot add duplicate memos",
  "e_1021": "The whitelist IP set has exceeded the maximum limit",
  "e_1022": "Exceeding the maximum creation limit of the API",
  "e_12301": "The account is abnormal. Please contact customer service",
  "e_12302": "You have exceeded the current withdrawal limit",
  "e_12303": "You have exceeded the number of withdrawals for the day",
  "e_12304": "Manual review",
  "e_12305": "After changing the security setting, you are not allowed to withdraw for the next 24 hours.",
  "e_12306": "Internal Error",
  "e_12307": "Enable at least 2 security verifications",
  "e_12308": "Withdrawal failed. The withdrawal amount cannot exceed the amount purchased within 24 hours of OTC.",
  "e_12503": "You are not allowed to deposit",
  "e_32092": "You are not allowed to sell",
  "e_32091": "You are not allowed to buy",
  "e_33001": "You are not allowed to trade",
  "e_12507": "You are not allowed to transfer to future account",
  "e_25220": "You are not allowed to open position",
  "e_25221": "You are not allowed to transfer to future account",
  "e_12514": "You are not allowed to transfer to Buy & Sell account",
  "e_24041": "Subscription input precision is not legal. Please enter again.",
  "e_24042": "Subscription input precision is not legal. Please enter again.",
  "e_24201": "Please re-enter the amount.",
  "e_24211": "You cannot subscribe now.",
  "e_24212": "There is not enough available quota, the available quota is {0}.",
  "e_24215": "The precision exceeds the limit. Please re-enter.",
  "e_24220": "Your subscription amount should be greater than the minimum limit",
  "e_24221": "Your subscription amount exceeds the maximum limit.",
  "e_24222": "The subscription is successful. Please do not repeat the operation",
  "e_24243": "Your balance is insufficient",
  "e_25002": "The coin does not exist. Please switch coin",
  "e_25201": "The transfer amount cannot be empty or less than or equal to 0",
  "e_25203": "Incorrect number of strokes. Please try again",
  "e_25204": "The transfer amount cannot be less than {0}USDT",
  "e_25211": "Over transferable balance, the transfer failed",
  "e_25212": "The transfer failed. Please try again",
  "e_25213": "The transfer failed and the service is temporarily unavailable.",
  "e_34001": "Product does not exist",
  "e_34002": "Insufficient balance",
  "e_34003": "Wrong order amount",
  "e_34004": "Insufficient product subscription quota",
  "e_34005": "Unavailable to subscribe or redeem during 00:00 to 00:15 UTC + 4",
  "e_34006": "User cumulative subscription exceed the limit",
  "e_34008": "You are not allowed to subscribe",
  "e_34009": "You are not allowed to redeem",
  "######用户限制错误码": "######用户限制错误码",
  "e_34011": "Sale stop",
  "e_34100": "System is busy now, please try again later",
  "e_34101": "System is busy now, please try again later",
  "e_34102": "Sorry, you did not participate.",
  "e_34103": "You have already participated. Please do not participate again.",
  "e_34104": "Exceeds the maximum number of ticket",
  "e_34105": "Insufficient available assests",
  "e_34106": "There are currently too many visitors, please try again later. You can participate during the participation period.",
  "e_34107": "System is busy now, please try again later",
  "e_34108": "System is busy now, please try again later",
  "e_34109": "The participation period has not started yet.",
  "e_34110": "There are currently too many visitors. Please try again later. You can participate during the participation period.",
  "e_34111": "Only users who complete KYC are qualified to participate.",
  "e_34112": "Sorry, you are not eligible for participation.",
  "e_34113": "Please input your ticket number.",
  "e_34114": "The minimum number of tickets is 1.",
  "e_34115": "Sorry, you are not eligible for participation.",
  "e_60023": "Please complete your personal verification(Starter)",
  "e_60024": "Sevices is not available in your countries and areas",
  "e_60025": "Please enable your Google/Phone/E-mail Authentication",
  "e_53002": "Please complete your personal verification(Advanced)",
  "e_32080": "Please complete your personal verification(Starter)",
  "e_32081": "Please complete your personal verification(Advanced)",
  "e_32082": "Please enable your Google/Phone/E-mail Authentication",
  "e_32083": "Sevices is not available in your countries and areas",
  "e_33115": "Please complete your personal verification(Advanced)",
  "e_33116": "Sevices is not available in your countries and areas",
  "e_12515": "Please complete your personal verification(Starter)",
  "e_12516": "Sevices is not available in your countries and areas",
  "e_2200": "Please enable your Google/Phone/E-mail Authentication",
  "e_17014": "Please complete your personal verification(Advanced)",
  "e_17015": "Sevices is not available in your countries and areas",
  "e_34015": "Please complete your personal verification(Advanced)",
  "e_34057": "The product you subscribed for is sold out/Stopped Sell, you can choose another product to re-initiate your application.",
  "e_34016": "Sevices is not available in your countries and areas",
  "e_34017": "User’s country is forbidden for BitMart Earn.",
  "e_32051": "The network fee has expired. Please resubmit your order.",
  "e_12517": "We will process your transfer request within 12 hours, and the contract transaction will not be affected during this period",
  "e_133000": "Professional users can not enjoy BMX discounts",
  "e_133001": "Special users can not enjoy BMX discounts",
  "e_33121": "Sorry, the status of your account is over-loss, you are prohibited from placing margin orders.",
  "e_33124": "size ≥ {0}",
  "e_33125": "price ≥ {0}",
  "e_33126": "size * price ≥ {0}",
  "e_33127": "notional ≥ {0}",
  "e_33128": "notional is too small",
  "e_33129": "size ≥ {0}",
  "e_33130": "size is too small",
  "e_35507": "Your transfer request is being processed, please kindly wait, thanks.",
  "e_35511": "You have unclosed positions or pending orders, please clear them before open credit-line service.",
  "e_40001": "Request Failed",
  "e_40011": "The modification status is incorrect and cannot be modified",
  "e_40012": "Invalid parameter",
  "e_40013": "Invalid signature",
  "e_40014": "Invitation ID is invalid",
  "e_40015": "Invited ID is invalid",
  "e_40016": "Invalid commission rate",
  "e_40017": "The invitee has become a partner already",
  "e_40018": "Invalid verification code",
  "e_40020": "Unable to retrieve user trading data",
  "e_40021": "Time format conversion failed",
  "e_40022": "http request failed",
  "e_40023": "Administrator ID cannot be null",
  "e_40024": "Unable to analysis the value",
  "e_40025": "Invalid User ID",
  "e_40026": "Invalid Administrator ID",
  "e_40027": "Contract account has not been opend",
  "e_40040": "type is null",
  "e_40043": "Query userid is a required parameter",
  "e_40044": "Query contractid is a required parameter",
  "e_40019": "AES encryption failed",
  "e_41323": "Credit funds cannot be used for collateral",
  "e_41324": "Asset transfer in progress, please try again later",
  "e_50001": "apply Fail",
  "e_50002": "Partner application data does not exist",
  "e_50004": "BD already exists",
  "e_50005": "BD does not exist",
  "e_50006": "Please relocate partners before remove",
  "e_50007": "No partner exists under you",
  "e_50008": "The partner does not exist",
  "e_50009": "Unable to review repeatedly",
  "e_50010": "You have been already a partner",
  "e_50011": "BD is unable to proceed the partner application",
  "e_50012": "Not qualified to be a BD",
  "e_50013": "Mail delivery failed",
  "e_36114": "Please try later, the metadata is updating now.",
  "e_36120": "Your account has not passed KYC, please complete KYC first.",
  "e_33134": "No permission for this pair",
  "e_36130": "The NFT trading function is not available in your country or area, please contact customer service if you have any questions.",
  "e_36131": "Please complete the identity verification Level 2 to ensure the account security, due to the large amount of transactions.",
  "e_33144": "This pair is abnormal or will be delist，suspend trading/borrowing/transfer.",
  "e_25900": "Unable to transfer as our copy trading feature does not support institutional accounts at this moment",
  "e_25901": "Institutional accounts cannot apply to become a master trader",
  "e_36000": "Request parameter exception",
  "e_36001": "Insert exception",
  "e_36002": "Update exception",
  "e_36003": "Query exception",
  "e_36004": "Delete exception",
  "e_36005": "Upload exception",
  "e_36006": "Upload file is empty",
  "e_36007": "Upload file format error",
  "e_36008": "Status is error",
  "e_36009": "Order status is error",
  "e_36010": "Upload file too large",
  "e_36020": "This user does not exist",
  "e_36021": "This creator does not exist",
  "e_36022": "This collectible does not exist",
  "e_36023": "This nft does not exist",
  "e_36024": "This show nft does not exist",
  "e_36025": "This storage info does not exist",
  "e_36026": "This order does not exist",
  "e_36027": "This collectible does not bind creator",
  "e_36028": "This airdrop does not exist",
  "e_36030": "This id does not exist",
  "e_36031": "This status is not storage",
  "e_36032": "This status is not on sale",
  "e_36033": "lack inventory",
  "e_36034": "create order error",
  "e_36035": "request feign fail",
  "e_36036": "get userInfo error",
  "e_36037": "not purchasable timing",
  "e_36038": "NFT has sold",
  "e_36039": "Login name is not correct",
  "e_36040": "sale time is error",
  "e_36041": "not has NFT",
  "e_36042": "account is not enough",
  "e_36043": "have no coin info",
  "e_36044": "system config not init or unknown network",
  "e_36045": "Risk operation,please try it again.",
  "e_36046": "account refund fail",
  "e_36047": "nft withdraw fail",
  "e_36048": "check gas fail",
  "e_36049": "withdraw fee changed",
  "e_36050": "exist nft is not this user",
  "e_36051": "http request fail",
  "e_36052": "do deduct fail",
  "e_36053": "The wallet is frozen,please check it.",
  "e_36054": "get dollar rate error",
  "e_36055": "Unlock nft or create order error",
  "e_36061": "query nft does not exist",
  "e_36062": "query chain nft has error",
  "e_36063": "has nftTokenId does not exist",
  "e_36064": "the nft status has been changed",
  "e_36065": "Risk operation,please try it in safe environment .",
  "e_36066": "System error,please try it again",
  "e_36067": "The blockchain is busy,please try it again",
  "e_36068": "NFT code is null",
  "e_36069": "Incorrect purchase, you are the owner of this item",
  "e_36070": "excel export error",
  "e_36071": "quantity not same",
  "e_36072": "airdrop task's status is not executable",
  "e_36073": "no airdrop detail",
  "e_36074": "airdrop check error,please check the fail reason",
  "e_36075": "airdrop execute fail",
  "e_36076": "IO exception",
  "e_36077": "enum does not exist.",
  "e_36096": "subtract nft quality fail",
  "e_36080": "Sorry, the NFT item can’t be purchased.",
  "e_36081": "Sorry, the NFT item can’t be listed.",
  "e_36082": "Sorry, you can’t deposit the NFT item.",
  "e_36083": "Sorry, you can’t withdraw the NFT item.",
  "e_36090": "Account has been frozen , pls contact with us.",
  "e_36091": "Withdraw prohibited, pls contact with us.",
  "e_36092": "Deposit prohibited, pls contact with us.",
  "e_36093": "Trading prohibited, pls contact with us.",
  "e_36094": "Listing prohibited, pls contact with us.",
  "e_36095": "Listing nft fail",
  "e_36097": "NFT quality is not enough",
  "e_36098": "Delisting nft fail",
  "e_36100": "This nft item does not exist",
  "e_36101": "purchase nft database error",
  "e_36102": "item data error",
  "e_36110": "upload result error.",
  "e_36111": "nft upload un done",
  "e_36112": "order type is wrong",
  "e_36113": "can not find deposit address",
  "e_36117": "token uri is null. ",
  "e_36118": "nft not set price",
  "e_36121": "This collectible is not online",
  "e_36122": "send message error",
  "e_36123": "transfer NFT error",
  "e_36124": "You have reached the purchase limit for the collection.",
  "e_36125": "transfer user error",
  "e_36126": "This item has order don`t finish",
  "e_33137": "The NFT trading function is not available in your country or area, please contact customer service if you have any questions.",
  "e_36127": "Please try later, frequent commit. ",
  "e_36128": "collectible error. ",
  "e_36129": "price error. ",
  "e_36132": "Server is crowded,please try later.",
  "e_36133": "has NFT is trading",
  "e_36134": "nft list price must not be greater than 100,000 usd.",
  "e_33138": "need QR code",
  "e_33135": "Your account has passed KYC-0, please complete KYC-1 first",
  "e_33136": "Your account has passed KYC-1, please complete KYC-2 first",
  "e_46001": "Due to server capacity constraints, each user can generate up to 5 times per month.",
  "e_2124": "No corresponding address was found.",
  "e_61008": "Suspend transfer out",
  "e_5113": "Suspend transfer out",
  "e_34059": "This order cannot be redeemed in advance, since you participated in the event",
  "e_34062": "Unfortunately, this service is not available for users from the selected states/regions/territories due to regulatory restrictions/concerns. Sorry for the inconvenience and we appreciate your kind support to BitMart.",
  "e_52001": "Size of trustIpList should be less than or equal to 10",
  "e_52002": "User could create at most 10 APIs",
  "e_52009": "Sub-account not found",
  "e_52010": "Not your sub-account",
  "e_52011": "Repeat request",
  "e_52012": "This account has been risk controlled",
  "e_41325": "This currency cannot be used as collateral",
  "e_41326": "Collateral cannot be increased for this currency",
  "e_41103": "This currency cannot be borrowed",
  "e_25903": "The daily limit for adding sub-affiliates has been reached today",
  "e_25904": "The operation is too frequent, please try again later.",
  "e_1764": "The account is not whitelisted, please contact the administrator to set it up",
  "e_2150": "Your account does not support Convert",
  "e_2151": "You have converted once today, please come back tomorrow",
  "e_2152": "The currency price fluctuates too much, please try again later.",
  "e_2153": "The amount of a single conversion shall not exceed 20U",
  "e_2154": "System error, please try again later",
  "e_2155": "Your account status is abnormal and cannot be converted",
  "e_2156": "Advanced Identity Verification needs to be completed first",
  "e_2157": "Insufficient balance",
  "e_40002": "Up to 5 deposit addresses can be generated.",
}